### ISSUE TITLE
(sweden) US paras should point to the paratrooper models, not the standard ones

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#100]
They have different skins/slightly different models. Also, worth considering if the removal of the paratrooper HP boost is intentional or not (in main they're 140hp, like british inf).

**Comment by ashdnazg** [comment]
Please check if this is solved.

**Comment by kanatohodets** [comment]
damnit, forgot about https://github.com/spring1944/spring1944/blob/sweden/gamedata/unitdefs_pre.lua#L98 -- that's what I get for leaving myself TODO notes without running spring. next time I'll assign to myself so it's clear I'm not asking someone to check for me :)

**Comment by ashdnazg** [comment]
Worse things have happened ^^
