### ISSUE TITLE
Stuck inf in barracks

### ISSUE THREAD

**Issue by ashdnazg** [spring1944/spring1944#101]
We all know what that means

**Comment by kanatohodets** [comment]
could this have been improved in a recent engine? I set up about 20 US rax in all orientations spamming rifle/assault squads for about 1.5 hours of gametime (50x speed), and didn't observe any stuck guys.

**Comment by ashdnazg** [comment]
No, try soviet rax, SMG always stuck

**Comment by kanatohodets** [comment]
optimistically closing after 0f942c8d -- it solved northern facing soviet rax, and didn't break a few others. if this is still a problem in places we can do something more aggressive like disable unit blocking for a few seconds after spawn, or spawn the dudes in sequence one by one.
