### ISSUE TITLE
Engineers ability to reclaim.

### ISSUE THREAD

**Issue by Lowdive** [spring1944/spring1944#105]
playtesting my changes to the AI buildorder I noticed engineers can't salvage trees or rocks or features, they try to, and hang the buildorder trying to salvage indefinitely.

Apparently its some kind of bug where, the first time you issue the command, it does nothing, you must issue the command more than once so that the salvage happens.

EDIT: forgot to mention it's on SWEDEN branch
SUPER EDIT: found out it's not due to missing canassist, canreclaim atributes, but rather because of a bug, edited the description accordingly.

**Comment by Lowdive** [comment]
I edited this issue, quite drastically, commenting it, in case edits don't flare up in mail.

**Comment by kanatohodets** [comment]
Lowdive: is this a bug in spring unit AI, in CRAIG, or somewhere else?

**Comment by Lowdive** [comment]
the AI part is misleading sorry, I'm guessing the bug would be either on
spring itself
or somwhere around the canreclaim-->salvage translation for s44

you can replicate it, on sweden just give the order to build on top of a
feature, and the engineer will hang there unless you specifically do the
reclaim order more than once on the feature that is obstructing your build
command.

On Wed, Jun 17, 2015 at 11:20 AM, Ben Tyler <notifications@github.com>
wrote:

> Lowdive: is this a bug in spring unit AI, in CRAIG, or somewhere else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/105#issuecomment-112866673>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>
