### ISSUE TITLE
US barracks can spawn boatyard truck inside another building

### ISSUE THREAD

**Issue by yuritch** [spring1944/spring1944#106]
As the title says: it's possible to place US barracks so close to another building that built trucks will end up inside that building, unable to leave it.

In this case we see a boat truck stuck inside US supply storage (not that it's wide to place buildings like that anyway...)
![rax_bug](https://cloud.githubusercontent.com/assets/6875715/8144691/d2319de6-11f2-11e5-998a-faa027f52821.png)

**Comment by yuritch** [comment]
This is because US barracks def has quite narrow footprint so the point where trucks spawn is outside the footprint (and so can be inside other buildings). Should I just increase the footprint? That will prevent trucks getting stuck in things, but it will also make barracks harder to place.

**Comment by FLOZi** [comment]
Solution could be to change location of truck building to across the back, or parallel to the sides with an increased footprint either way.

**Comment by sanguinariojoe** [comment]
@yuritch Is this fixed??

**Comment by yuritch** [comment]
Not quite. The truck does not spawn inside the other building anymore, but now a barracks placed like that just cannot build anything. Not even the infantry who are not produced at the side pad.
We could increase the footprint of the barracks to prevent that, but then it will be harded to place it on uneven terrain. So the current approach has its upsides and downsides.
