### ISSUE TITLE
scout binocs don't work on water

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#107]
likely the weapon doesn't allow targeting the water surface?

**Comment by yuritch** [comment]
This seems to be a related engine mantis report:
https://springrts.com/mantis/view.php?id=4810

Basically ground-only weapons (supposedly) cannot target water surface anymore.

**Comment by ashdnazg** [comment]
yup

**Comment by kanatohodets** [comment]
fixed in spring develop bf08f390 -- @ashdnazg is awesome :+1:
