### ISSUE TITLE
SWEDEN: On death, some units send this error: Could not load model.

### ISSUE THREAD

**Issue by Lowdive** [spring1944/spring1944#109]
[f=0025442] Warning: could not load model "gerjagdpanzeriv.s3o" (reason: [S3OParser] could not find model-file objects3d/gerjagdpanzeriv.s3o)
...
[f=0029165] Warning: could not load model "itabreda61.s3o" (reason: [S3OParser] could not find model-file objects3d/itabreda61.s3o)

if it's looking for that specific s3o at objects3d/, only _damaged and _destroyed variants are there.
objects3d/ger/guns is where gerjagdpanzeriv.s3o is...

**Comment by kanatohodets** [comment]
Fixed these up, thanks @Lowdive!
