### ISSUE TITLE
Add turretturnspeed to loads of units

### ISSUE THREAD

**Issue by ashdnazg** [spring1944/spring1944#111]
Some false positives, but most of these need a value:

[f=0000000] Warning: No turret turn speed for M4 GAZ-AAA
[f=0000000] Warning: No turret turn speed for Deployed PvLv m/40 AT Tripod
[f=0000000] Warning: No turret turn speed for Towed Type 90 75mm Gun
[f=0000000] Warning: No turret turn speed for Deployed MG42 Heavy Machinegun
[f=0000000] Warning: No turret turn speed for SdKfz 162 JagdPanzer IV/70(V)
[f=0000000] Warning: No turret turn speed for Deployed Kulsprutegevär m/36 Heavy Machinegun
[f=0000000] Warning: No turret turn speed for Towed Cannone da 75/32
[f=0000000] Warning: No turret turn speed for Wasp Mk.II
[f=0000000] Warning: No turret turn speed for M3A1 Halftrack
[f=0000000] Warning: No turret turn speed for Deployed Q.F. 17 Pounder
[f=0000000] Warning: No turret turn speed for SdKfz 142/1 StuG III Ausf. G
[f=0000000] Warning: No turret turn speed for T-70/M42
[f=0000000] Warning: No turret turn speed for Type 1 Ho-Ni I
[f=0000000] Warning: No turret turn speed for Autocannone 90/53 su Lancia 3Ro
[f=0000000] Warning: No turret turn speed for SdKfz 138 Panzerjäger Marder III Ausf. M
[f=0000000] Warning: No turret turn speed for Deployed 15cm Nebelwerfer 41
[f=0000000] Warning: No turret turn speed for SdKfz 10/5
[f=0000000] Warning: No turret turn speed for Semovente da 75/18
[f=0000000] Warning: No turret turn speed for Ram Kangaroo
[f=0000000] Warning: No turret turn speed for Type 2 Ho-Ni II
[f=0000000] Warning: No turret turn speed for Autocannone da 100/17
[f=0000000] Warning: No turret turn speed for Semovente da 90/53
[f=0000000] Warning: No turret turn speed for Type 97 Te-Ke
[f=0000000] Warning: No turret turn speed for SU-85
[f=0000000] Warning: No turret turn speed for Deployed 57mm ZiS-2
[f=0000000] Warning: No turret turn speed for Deployed Type 92 Heavy Machinegun
[f=0000000] Warning: No turret turn speed for Semovente da 75/46
[f=0000000] Warning: No turret turn speed for Deployed Vickers Mk I Heavy Machinegun
[f=0000000] Warning: No turret turn speed for Type 2 Ka-Mi
[f=0000000] Warning: No turret turn speed for Carro Pesante P26/40
[f=0000000] Warning: No turret turn speed for Autocannone Breda da 20 mm A/A su Fiat-SPA Dovunque 35
[f=0000000] Warning: No turret turn speed for Autoblinda AB-41
[f=0000000] Warning: No turret turn speed for Deployed 76mm ZiS-3
[f=0000000] Warning: No turret turn speed for Type 97 Chi-Ha
[f=0000000] Warning: No turret turn speed for Type 97 Chi-Ha
[f=0000000] Warning: No turret turn speed for Stridsvagn m/41 SII
[f=0000000] Warning: No turret turn speed for Stridsvagn m/42
[f=0000000] Warning: No turret turn speed for Deployed Obice da 100/22
[f=0000000] Warning: No turret turn speed for Semovente da 47/32
[f=0000000] Warning: No turret turn speed for Deployed Cannone da 47/32
[f=0000000] Warning: No turret turn speed for Deployed 5.7cm PvKan m/43
[f=0000000] Warning: No turret turn speed for M5 Halftrack
[f=0000000] Warning: No turret turn speed for M16 MGMC
[f=0000000] Warning: No turret turn speed for M5 Halftrack
[f=0000000] Warning: No turret turn speed for LVT(A)-4
[f=0000000] Warning: No turret turn speed for Carro Mediuo M15/42
[f=0000000] Warning: No turret turn speed for Deployed Vickers Mk I Heavy Machinegun
[f=0000000] Warning: No turret turn speed for Deployed Vickers Mk I Heavy Machinegun
[f=0000000] Warning: No turret turn speed for M7 HMC Priest
[f=0000000] Warning: No turret turn speed for Deployed 3-Inch M5
[f=0000000] Warning: No turret turn speed for Deployed 105mm M2
[f=0000000] Warning: No turret turn speed for Deployed 122mm M-30
[f=0000000] Warning: No turret turn speed for PzKpfw III Ausf L
[f=0000000] Warning: No turret turn speed for L6/40 Lancia Flamme
[f=0000000] Warning: No turret turn speed for PBil m/40 Lynx
[f=0000000] Warning: No turret turn speed for PBil m/31 w/ 20mm Bofors m/40
[f=0000000] Warning: No turret turn speed for Stridsvagn m/40
[f=0000000] Warning: No turret turn speed for Stridsvagn m/37
[f=0000000] Warning: No turret turn speed for SdKfz 173 JagdPanther
[f=0000000] Warning: No turret turn speed for Type 4 Ka-Tsu
[f=0000000] Warning: No turret turn speed for Autocannone da 75/27
[f=0000000] Warning: No turret turn speed for Deployed 7,5cm Kanon m/02-33
[f=0000000] Warning: No turret turn speed for Deployed 10.5cm Haubits m/39
[f=0000000] Warning: No turret turn speed for BA-64
[f=0000000] Warning: No turret turn speed for T-60/M41
[f=0000000] Warning: No turret turn speed for Type 3 Chi-Nu
[f=0000000] Warning: No turret turn speed for Deployed 10.5cm LeFH 18M
[f=0000000] Warning: No turret turn speed for Deployed Maxim PM 1910 Heavy Machinegun
[f=0000000] Warning: No turret turn speed for SU-76
[f=0000000] Warning: No turret turn speed for SU-100
[f=0000000] Warning: No turret turn speed for ISU-152
[f=0000000] Warning: No turret turn speed for Type 95 Ha-Go
[f=0000000] Warning: No turret turn speed for Deployed Type 1 47mm Gun
[f=0000000] Warning: No turret turn speed for Type 97 Te-Ke
[f=0000000] Warning: No turret turn speed for Type 1 Chi-He
[f=0000000] Warning: No turret turn speed for Type 97 Shinhoto Chi-Ha
[f=0000000] Warning: No turret turn speed for Type 4 Ho-Ro
[f=0000000] Warning: No turret turn speed for Carro Protetto A.S. 37
[f=0000000] Warning: No turret turn speed for Deployed Type 91 105mm Howitzer
[f=0000000] Warning: No turret turn speed for Type 3 Ho-Ni III
[f=0000000] Warning: No turret turn speed for SAV m/43
[f=0000000] Warning: No turret turn speed for Semovente da 105/25
[f=0000000] Warning: No turret turn speed for Deployed 7.5cm PaK 40
[f=0000000] Warning: No turret turn speed for SdKfz 124 Wespe
[f=0000000] Warning: No turret turn speed for SdKfz 251/1 Halftrack
[f=0000000] Warning: No turret turn speed for 25pdr SP Sexton Mk. II
[f=0000000] Warning: No turret turn speed for Type 94 Isuzu w/ Type 98 20mm AA
[f=0000000] Warning: No turret turn speed for Deployed Breda M37 Heavy Machinegun
[f=0000000] Warning: No turret turn speed for Deployed Q.F. 25 Pounder

**Comment by kanatohodets** [comment]
turretturnspeed -- any thoughts on a good heuristic? (not subject to fear || ship turret) && has weapons was my first thought, but that fails on the boat mothers, assault guns, mines, kangaroo, and turretless TDs

**Comment by FLOZi** [comment]
You dislike the default value that much?

**Comment by ashdnazg** [comment]
I think it doesn't fit some of the units (such as halftrack)

**Comment by yuritch** [comment]
All unit classes have defaults now, as per e2882f50df6d25d454b2db19be2e4cff6d002876
