### ISSUE TITLE
Fix errorspam from lock camera in new camera mode.

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#113]
Perhaps by just turning it off?

**Comment by ashdnazg** [comment]
I already turned it off, apparently it's not enough, so removing may be an option.

**Comment by kanatohodets** [comment]
Fixed in 714207b3c2e.

There was some discussion for improvement of this widget:
* Drop all the code related to camera formats and have the protocol always include all of the parameters required for SetCameraState. This would allow it to gracefully handle changing camera types by the broadcaster.
* Transform the broadcast code into an unsynced gadget so that all players are always broadcasting, and then only show the UI for subscribing to broadcasts if the user is a spectator. This handles my main objection to the widget as a player, which is that it gets in my way on the screen while playing.
