### ISSUE TITLE
artillery can keep zeroed-in accuracy between area attack orders

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#114]
10:43 < kmar> set arty to area attack on ground with los - they get perfect accuracy - then set them to area attack a place without los (don't cancel anything, just re-issue the area-attack) - they show they don't have los, but they keep perfect accuracy

**Comment by ashdnazg** [comment]
https://github.com/spring1944/spring1944/commit/b8fc515e199119e5215792e46e98fd5125edcbaf
