### ISSUE TITLE
Integrate Scenario Editor with S44

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#121]
gajop has been working on a super cool ingame mission editor. Integrating it with S44 shouldn't be too hard, and it is the first step towards producing tutorials/missions/MP scenarios/etc.

Main library:
https://github.com/gajop/Scenario-Editor-Core

Game integrations:
https://github.com/gajop/Scenario-Editor-BA
https://github.com/gajop/Scenario-Editor-ZK
https://github.com/gajop/Scenario-Editor-EVO

**Comment by Lowdive** [comment]
YES YES YES YES YES YES

On Tue, Jul 7, 2015 at 8:39 AM, Ben Tyler <notifications@github.com> wrote:

> gajop has been working on a super cool ingame mission editor. Integrating
> it with S44 shouldn't be too hard, and it is the first step towards
> producing tutorials/missions/MP scenarios/etc.
>
> Main library:
> https://github.com/gajop/Scenario-Editor-Core
>
> Game integrations:
> https://github.com/gajop/Scenario-Editor-BA
> https://github.com/gajop/Scenario-Editor-ZK
> https://github.com/gajop/Scenario-Editor-EVO
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/121>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by kanatohodets** [comment]
done in a basic way: https://github.com/spring1944/Scenario-Editor-S44

If you're excited about this, you'll need to do the following in your games directory (where your copy of S44 git already lives):

    git clone --recursive https://github.com/gajop/Scenario-Editor-Core.git scened.sdd
    pr-downloader --download-archive spring-features:stable
    git clone https://github.com/spring1944/Scenario-Editor-S44.git s44-scened.sdd

If you have any trouble, let's start gathering issues/suggestions on the https://github.com/spring1944/Scenario-Editor-S44 repo.

make sure to let us know if you make anything cool, @Lowdive :)

**Comment by Lowdive** [comment]
followed instructions I'll point out corrections I had to make in order for
everything to work:

--download-archive, I changed for: --download-game

and for the Scenario Editor S44 I had to change the modinfo, since it
was depending on Spring: 1944 $VERSION, the correct dependant (for me
at least) is: Spring: 1944 dev-$VERSION

it was throwing errors otherwise.

And it's alive, at least it opens and I can see the GUI and all...

I'll check it out later when I get out of work.

:D


On Mon, Jul 13, 2015 at 8:17 AM, Ben Tyler <notifications@github.com> wrote:

> done in a basic way: https://github.com/spring1944/Scenario-Editor-S44
>
> If you're excited about this, you'll need to do the following in your
> games directory (where your copy of S44 git already lives):
>
> git clone --recursive https://github.com/gajop/Scenario-Editor-Core.git scened.sdd
> pr-downloader --download-archive spring-features:stable
> git clone https://github.com/spring1944/Scenario-Editor-S44.git s44-scened.sdd
>
> If you have any trouble, let's start gathering issues/suggestions on the
> https://github.com/spring1944/Scenario-Editor-S44 repo.
>
> make sure to let us know if you make anything cool, @Lowdive
> <https://github.com/Lowdive> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/121#issuecomment-120924201>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by kanatohodets** [comment]
@Lowdive oh, yeah, sorry, I wrote download-archive from memory. for dev-$VERSION vs $VERSION, you just need to update your S44 git repo :) we removed 'dev-' because it means we can do rapid stable releases more cleanly.

good luck!

**Comment by Lowdive** [comment]
my bad, that's what I get for browsing all the commits at the github webpage instead of actually syncing daily...

**Comment by kanatohodets** [comment]
no worries :P there are still quite some issues, as you already mentioned on the other repo. I was going to look at them tonight but ended up playing a few games. tomorrow!
