### ISSUE TITLE
remove Clone/Append from defs in _post to avoid 'unknown tag' warnings

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#122]
Spring 99+ warns when it loads weapondefs with unknown tags. We have custom things there for generating stuff using OO defs, so we need to filter those out before the WeaponDef parser sees them.

**Comment by ashdnazg** [comment]
fixed in https://github.com/spring1944/spring1944/commit/84ebf8c0f8201fc18985c5f19332e20592fd1ad4
