### ISSUE TITLE
sweden: HQs spawn with wrong set of units

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#123]
Somehow in sweden HQ spawn defs are mismatched with commanders:

#### Soviet spawn #1: 
![Soviet spawn #1](http://i.imgur.com/160nYkK.jpg)

#### Soviet spawn #2: 
![Soviet spawn #2](http://i.imgur.com/C73RuFY.jpg)

**Comment by ashdnazg** [comment]
Fixed in https://github.com/spring1944/spring1944/commit/6dba17f93e0ac06e7f4200531fc8525605ea8efd

seemed to be caused in https://github.com/spring1944/spring1944/pull/115
@Lowdive I assume there was a reason I'm not aware of for adding this line?

**Comment by Lowdive** [comment]
bad cleanup on my part
