### ISSUE TITLE
Infantry remains stationary after being pinned

### ISSUE THREAD

**Issue by Godde** [spring1944/spring1944#126]
When infantry gets pinned they will remain stationary even after fear is removed. They will only move after you reissue their orders.

**Comment by Godde** [comment]
<[S44]yuritch> engine does not reset 'wanted speed' 
<[S44]yuritch> it used to some versions back

**Comment by yuritch** [comment]
Proposed solution: gadget or lus can re-issue current order as soon as the pinning is over (speed is restored). This way the engine will notice speed change and unit will start moving

**Comment by yuritch** [comment]
Or a rather more radical solution: can someone (hoko?) check if it would be possible to have the engine re-assign 'wanted speed' to units which had some change to their max speed? This should be easy to track engine side. It used to be like that some years ago.

**Comment by yuritch** [comment]
Would solve problems with: inf, inf guns, katyusha, amphibs, maybe others

**Comment by ashdnazg** [comment]
already fixed in sweden.

**Comment by ashdnazg** [comment]
I'll check the engine though
