### ISSUE TITLE
UI suggestions from Silverfox

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#127]
> 14:44 < Silverfox85> I have some suggestions/comments about the new UI
> 14:45 < Silverfox85> Concerning the life-bar and unit symbol below units (when zoomed in): The unit symbol should be centered above the life-bar, not to the left of it.
> 14:47 < Silverfox85> Reason: This makes the physical position of the unit more intuitive to decern in a fraction of a second unpon the player zooming in from a state of viewing only symbols to a state of viewing life-bar/3D-model/symbol.
> 14:48 < Silverfox85> Additionally: The symbol in the life-bar/3D-model/symbol state should support the symbol changing white when the unit is selected, just like the symbols change white when in  only-symbol viewing state (zoomed out).
> 14:50 < Silverfox85> Reason: Again, this is too make it easier for the player to quickly physically assess the position of the units he was just viewing in zoomed-out state, upon changing to a zoomed-in state.
> 14:50 < Silverfox85> (The units he had selected, that is).
> 14:53 < Silverfox85> I understand that there is the "high-lighted" circle that appears beneath units in the zoomed-in or life-bar/3D-model/symbol state, however, I would not be making these suggestions if this current "high-lighting" method

**Comment by sanguinariojoe** [comment]
Noone is interested on this, apparently
