### ISSUE TITLE
Adopt some changes from S44equilibrio

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#129]
- [ ] reduced unit turn rate on SP guns / tanks; TDs are a little fast to turn to kill flanking units
- [ ] bump AA reload rate: nerfs them against infantry, makes AA/air interactions more understandable; need to be careful not to make air too powerful.
- [ ] hide mine decals, perhaps?
- [ ] bump kinetic damage a bit: it restores a bit of balance to the dynamic between sniper tanks and rushing mediums without introducing a totally new mechanic like wear or tracking; also makes flanking/surprise a bigger bonus. JAL bumped by 20%; I might go 10-15%.

**Comment by yuritch** [comment]
Not relevant anymore, Sweden merge changed a lot
