### ISSUE TITLE
Interceptor sortie on fight targets buildings / tanks [4393-734dbab]

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#131]
And they kill buildings too! Faster than t-34!

**Comment by kanatohodets** [comment]
to recap from chat:

I couldn't reproduce this targeting behavior with the following test:

Ordered spitfires and set them to 'fight' towards a group of enemy inf halfway across the map (in LoS), with an enemy barracks (also in LoS) along the way.

They did not attempt to shoot at the rax -- ignored it as expected.

**Comment by buumi** [comment]
Ok tried it too again as reported this right after a multiplayer game. I don't see buildings being targeted with Fight command. Against tanks my Spitfires shoot occasionally but I think they weren't targeted. On the other hand you can assign building as a target (even one that isn't producing anything) and one Spitfire squad for example kills tank yard in just one approach.

**Comment by kanatohodets** [comment]
ok, cool. the easy way to fix that is just cheat and nerf damage from air cannons to buildings -- spitfires just pump out too much 20mm HE...

alternatively we could give plane weapons ammo and the player can just choose if it makes sense to spend all the ammo on murdering buildings, but I feel like that'd be bad complexity.
