### ISSUE TITLE
GBR mortar fired very rapidly [4393-734dbab]

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#133]
My logistics went down in very short time with one mortar squad. It fires like once per second.

**Comment by buumi** [comment]
I can't reproduce on single player. Maybe it was due to some of those script failures?

**Comment by ashdnazg** [comment]
I suspect it happens when the mortar gets out of ammo and resupplied while it's firing

**Comment by kanatohodets** [comment]
Bingo -- just reproduced it that way (out of ammo resupplying while firing)

**Comment by ashdnazg** [comment]
blocking out of ammo firing should go to script and not use reload

**Comment by kanatohodets** [comment]
:+1:

**Comment by kanatohodets** [comment]
This is even more amusing with JPN rocket mortars -- a rocket every second as long as you have logistics :)
