### ISSUE TITLE
Storages being killed by air possibly in weird way [4393-734dbab]

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#134]
I'm not sure about this one but it felt like sometimes storages got killed much faster than they normally would from planes' MG fire (which is quite slow because of storages' armor). I asked Nemo if he was artying that area and he said he wasn't yet two alive storages got destroyed in matter of seconds.

**Comment by yuritch** [comment]
Storage armor is directional, it has 30 top armor, 15 armor from the sides but 0 from front and rear. Could it be that planes were attacking from one of those directions? (they would need to be flying quite low for the hits to be considered front/rear instead of top)
