### ISSUE TITLE
[f=0013587] Error: [GetFeatureDef] could not find FeatureDef "itaassaultboat_dead"

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#137]

**Comment by yuritch** [comment]
Likely happens with all side-specific *assaultboat and *pontoonraft units - autogeneration gives them <SIDE>assaultboat_dead (or similar for pontoonraft) corpses, which do not exist.

Added code to boats.lua to remove corpse tag for those unit types since none of them actually has a model for such.
