### ISSUE TITLE
GBRStorageCamo remodel

### ISSUE THREAD

**Issue by FLOZi** [spring1944/spring1944#14]
Storage Camo should have a custom model, atm it has some model cobbled together from old small logistics. IMO a standard storage shed with either camo net over it or just a camo texture applied + some extra sandbags or such..

**Comment by yuritch** [comment]
Oops, didn't notice it was already modeled. Now we have 2 camo storage models.

**Comment by FLOZi** [comment]
Mine isn't great

**Comment by yuritch** [comment]
So now we have the models, this can be closed?

**Comment by kanatohodets** [comment]
yep! :D
