### ISSUE TITLE
At least some other planes don't fight P-51

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#149]
I tried with BF-109, FW-190 and Japanese planes and none attacked P-51. Either many fighters are broken or then there's something about P-51 so that no one wants to face it..

**Comment by Lowdive** [comment]
Prolly the latter, there's much to fear about a bubbly canopy, 6x12.5mm
MG's, sturdy body and "better" high-alt performance.

On Mon, Nov 9, 2015 at 1:26 PM, buumi <notifications@github.com> wrote:

> I tried with BF-109, FW-190 and Japanese planes and none attacked P-51.
> Either many fighters are broken or then there's something about P-51 so
> that no one wants to face it..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/149>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by kanatohodets** [comment]
I think this is a general problem with all AirAutoCannon weapons. still digging.
