### ISSUE TITLE
jpnkatsu transport squad is bugged

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#153]
When you build the Hoha halftrack , it had preloaded infantry, it doesnt come with the load but you pay the command for them.

**Comment by ashdnazg** [comment]
I wanted to remove the preloaded inf I think. not sure if it's the reason

**Comment by jal76** [comment]
same with jpnkatsu? It has still its preloaded infantry and its bugged.

**Comment by sanguinariojoe** [comment]
Is not broken anymore, AFAIK
