### ISSUE TITLE
Big supply radius points with some ATI cards

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#155]
I think it is related to this old bug: https://springrts.com/phpbb/viewtopic.php?f=11&t=24036
I have had it for very long time with FGLRX drivers on Linux (see screenshot below) but now I decided to investigate it more for the first time. I think I also found the fix which was as simple as changing GL.POINTS calls in the widget to GL.LINES. Of course that changes appearance a bit but I don't think it's only to worse.. Do you think this change could have some other issues with it?

![screenshot from 2015-12-04 23 46 31](https://cloud.githubusercontent.com/assets/4021203/11603279/5c766db8-9ae9-11e5-9f49-a119f06fe92f.png)

**Comment by Lowdive** [comment]
YES, a thousand times yes, it's annoying as hell.

On Fri, Dec 4, 2015 at 4:47 PM, buumi <notifications@github.com> wrote:

> I think it is related to this old bug:
> https://springrts.com/phpbb/viewtopic.php?f=11&t=24036
> I have had it for very long time FGLRX drivers on Linux (see screenshot
> below) but now I decided to investigate it more for the first time. I think
> I also found the fix which was as simple as changing GL.POINTS calls in the
> widget to GL.LINES. Of course that changes appearance a bit but I don't
> think it's only to worse.. Do you think this change could have some other
> issues with it?
>
> [image: screenshot from 2015-12-04 23 46 31]
> <https://cloud.githubusercontent.com/assets/4021203/11603279/5c766db8-9ae9-11e5-9f49-a119f06fe92f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/155>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by buumi** [comment]
On actual game i noticed the fix makes it look a bit ugly on some situations, mainly when there are multiple depots covering single area. Much better than original one for us who have this issue but for others it would need a bit more fixing..

**Comment by buumi** [comment]
So made a test and changing GL.POINTS to GL.LINES in supplyradius widget also solves the issue of supply radius not being visible at all with my Intel integrated GPU. Just a FYI if someone has issue with supply radiuses on Intel, this is at least a workaround. (A bit ugly on some cases like mentioned in previous comment)

**Comment by ashdnazg** [comment]
GL.POINT is highly buggy on anything but nvidia it seems

**Comment by buumi** [comment]
Can't test now but thanks for looking into this!

**Comment by Lowdive** [comment]
I can test it.

**Comment by ashdnazg** [comment]
well?
don't leave us hanging! :D

**Comment by Lowdive** [comment]
Ok, testing it with my ATI Radeon HD 6480G, it no longer shows big sized circles, tested on 4 games.
:)
