### ISSUE TITLE
Operation neptune v1.7 error on load

### ISSUE THREAD

**Issue by Skyraider2** [spring1944/spring1944#156]
error on load operation neptune in spring lobby
![sem titulo](https://cloud.githubusercontent.com/assets/16209043/11657887/cd255898-9da6-11e5-9e0e-36398465844f.png)

**Comment by kanatohodets** [comment]
Hi Skyraider2 -- thanks for reporting this! Does this also happen with [v2.0 - link](http://springfiles.com/spring/games/spring-1944-1)? 1.7 is a bit old at this point: how did you find it? I'll update the description on Springfiles to make things more clear.

**Comment by Skyraider2** [comment]
thanks kanatohodets,I am new to the game and I want this version, I already have the Operating gardem market, but I want one with ships

**Comment by ashdnazg** [comment]
v2.0 is more recent than v1.7
Also make sure you are using a recent engine:
http://sourceforge.net/projects/springrts/files/springrts/spring-100.0/spring_100.0.exe/download
