### ISSUE TITLE
How to make a ships in game?

### ISSUE THREAD

**Issue by Skyraider2** [spring1944/spring1944#158]
how to build ships in the game? I already have the overlord 2.0 Operating working

**Comment by Lowdive** [comment]
That's great! Now you need to build a deployable pontoon truck afaik, it
can be build from a barracks or from a vehicle yard. Then take that pontoon
truck to the sea and deploy it. It will deploy into a small ship building
facility, and then you can build boats.

On Thu, Dec 10, 2015 at 3:17 PM, Skyraider2 <notifications@github.com>
wrote:

> how to build ships in the game? I already have the overlord 2.0 Operating
> working
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/158>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by ashdnazg** [comment]
Only from a barracks.

**Comment by Lowdive** [comment]
I stand corrected.

On Thu, Dec 10, 2015 at 4:45 PM, Eshed <notifications@github.com> wrote:

> Only from a barracks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/158#issuecomment-163776059>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by Skyraider2** [comment]
thanks for help
