### ISSUE TITLE
Air icons widget

### ISSUE THREAD

**Issue by SuperKmar** [spring1944/spring1944#160]
not sure if this belongs here, as this is not an issue, but more of a suggestion

The air icons widget is useful, but not really informative. I suggest several upgrades to both use and information value (some might be easy, others probably not):

1) on the icons themselvs, display fuel time left as a pie countdown (like the sidebar build menu) with max vale being set as the fuel the moment the plane enters the field. (to distinguish one plane from another by battlefield entry time)

2) just above the icons, display a thin bar of HP (to distinguish one plane from another by combat history)

3) add shift clicking to select multiple planes

4) when hovering over an icon, show a huge green (or playercolor) arrow near the edges of the screen to the direction of the plane if it's offscreen or highlight it with some large green (or playercolor) circle or something if it's on screen. The idea behind this is that due to how fast air works and how fast AA kills it if mismanaged, you don't need to work with any other information if you are currently working with air.

5) maybe seperate widget to highlight enemy aircraft in los in a similar fasion as the above point. Same reasoning behind it. Maybe only do this if you have active air forces/

Sorry if i put this in the wrong place.

**Comment by SuperKmar** [comment]
1) Done, but in text form, since s44 fuel is kinda weird
2) Done
3) Done
4) just some circles for now, gl didn't agree with me on how i wanted this done. Still plenty helpful. Will update this later on when i get a bigger brain.
5) Decided against it for now... probably not as good an idea as i thought initially.

**Comment by sanguinariojoe** [comment]
So it is fixed
