### ISSUE TITLE
WeaponDefs can not be printed with printTable (widget)

### ISSUE THREAD

**Issue by yuritch** [spring1944/spring1944#161]
I tried to dump ingame WeaponDefs using a widget.
Code was this (I copied printTable from unitdefs_pre into my widget so it is always visible):
    printTable(WeaponDefs, 0)
    printTable(UnitDefs, 0)
UnitDefs printed fine, but WeaponDefs seem to only contain 2 functions (pairs and next) and no actual data for each weapon:
[f=0000000] ============================================================
[f=0000000] 0: 
[f=0000000]   next = <function>
[f=0000000]   pairs = <function>
[f=0000000] 1: 
[f=0000000]   next = <function>
[f=0000000]   pairs = <function>
(etc., up to 284)

Tried to do same by just looping WeaponDefs using pairs() and got a very similar result - each weapon def only contains 2 functions and no data.

**Comment by sanguinariojoe** [comment]
With the wiki stuff this is not required anymore, right?
