### ISSUE TITLE
EXP Increasing artillery rate of fire

### ISSUE THREAD

**Issue by SuperKmar** [spring1944/spring1944#162]
http://replays.springrts.com/replay/e131db567ea730ba71a55308e2a599f2

start at about 1:30 (this is a 2 hour game)

at about 1:45 we noticed a rapid fireing wespe and soon after and italian howitzer fireing faster than a rifleman!

I'm pretty sure it just got a lot of exp for killing something at random, although i can't really be sure about this

**Comment by yuritch** [comment]
That was in 2.0, right? Can you test a similar case in master? (since fixes for 2.0 are very unlikely and master has a very different internals)

**Comment by buumi** [comment]
I might be wrong but I thought #133 fixed this in master and that this still happens in 2.0 just much more seldom?

**Comment by SuperKmar** [comment]
#133 doesn't quite seem to be the same thing - since we could not reproduce the effect in-game at the time of discovery.
The units obsereved (wespe (kmar), ita howitzer (JAL)) were not alone, always in supply and i don't think i always ran out of ammo, but can't be sure about that either.

Yet only one wespe and only one cannone had rapid fire on them. Newly made wespe's did not inherit or get this upgrade, the original wespe did not lose it's bonus over several refills.

Both units had about 90 - 95% reload right after fireing, instead of the 0% for new units. 

If these are the same symptoms as #133 (Unit specific, not unit type or ammo use specific; noticable by observing reload bar - it does not reset to 0), then i agree that this is a duplicate bug.

I suggested this was exp based as i observe the same thing when a Zis-2 kills something and gets a bunch of exp in return - it's fire rate gets boosted by shifting the amount of reload the unit has left right after fireing.

**Comment by buumi** [comment]
Yeah just a guess. #133 wasn't unit specific and symptoms were the same (reload bar did not reset to 0) and it did not lose the bonus over several refills. I also think (not 100% sure) that Nemo said #133 was probably present in 2.0 too but not as regularly as in master. From replay exp of Wespe was at least reported as 0 like it should be.

**Comment by sanguinariojoe** [comment]
It seems this is not a problem anymore
