### ISSUE TITLE
T-34 targeted enemy mines [4507]

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#164]
On game with JAL he built mines as Soviets and my T-34 kept firing those without ordering them to.

**Comment by buumi** [comment]
Some units also keep firing enemy flags. Replay as an attachment if you want to see 2vs2 on 100.0 with S44 test-4565 (d755349) for yourself.
[20160403_220116_1944_Terra_Firma_100.sdf.zip](https://github.com/spring1944/spring1944/files/201533/20160403_220116_1944_Terra_Firma_100.sdf.zip)

**Comment by ashdnazg** [comment]
https://github.com/spring1944/spring1944/commit/11455bc78d97675c2ec1608dd140166e9777dc30

**Comment by yuritch** [comment]
Uncommenting some debug code in weapondefs_post shows that all HE guns (and only HE, because AA and AP are good) get nil as onlytargetcategory. Investigating this now

**Comment by ashdnazg** [comment]
I suggest not touching weapondef code before @kanatohodets updates it to the new model in order to prevent duplicate work

**Comment by yuritch** [comment]
The code was not changed except 1 debug line.
Onlytargetcategory is fixed now btw - cannon.lua had it for AP and AA, but not HE base class

**Comment by yuritch** [comment]
JAL confirms it's fixed with d755349. Reopen if not.

**Comment by kanatohodets** [comment]
Don't worry about changing unitdefs_post or weapondefs_post -- my changes are all in _pre (or in defs.lua/unitdefs.lua). unitdefs_pre is probably going away, but the defs should be the same by the time they hit *_post (or else I would have really broken stuff).

**Comment by yuritch** [comment]
_post change was just a debug echo.

Fix was in cannon.lua - there was no default onlytargetcategory set for HE class (while is was set for AP and AA), and so all HE cannon weapons tried to shoot at everything.
