### ISSUE TITLE
master is not spring100 compatible now

### ISSUE THREAD

**Issue by yuritch** [spring1944/spring1944#167]
When creating any unit with weapon toggle button (like all mortars, howitzers and even tanks), the following error is logged in master on spring 100:

[f=0000730] Error: LuaRules::RunCallIn: error = 2, UnitCreated, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_weapontoggle.lua"]:102: Unknown cmdDesc parameter queueing

Afterwards the unit lacks weapon toggle button.

There is also an error with widget:
[f=0000000] [widgets.lua] Error: Failed to load: camera_lockcamera.lua  (error = 2, LuaRules/Includes/camera.lua, [string "LuaRules/Includes/camera.lua"]:17: bad argument #2 to 'SetCameraState' (number expected, got no value))

**Comment by ashdnazg** [comment]
Oops

**Comment by ashdnazg** [comment]
I'll put the 102 changes in a branch if you want

**Comment by yuritch** [comment]
I think a branch would be good, because there probably are a lot of other changes needed to make it 101+ compatible. Doing them in master means it won't be compatible with either 100 or 102

**Comment by ashdnazg** [comment]
not that many.
I have them unpushed on my repo :D
