### ISSUE TITLE
Me 210 with rockets

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#170]
the Me 210 with Nebelwerferrockets throws errors while attacking.

f=0019185] [unit_script.lua] Error: [string "LuaRules/Gadgets/unit_script.lua"]:429: bad argument #1 to 'sp_SetPieceVisibility' (number expected, got nil)
[f=0019185] [UnitScript] Error: QueryWeapon: bad return value, expected number
[f=0019185] [unit_script.lua] Error: [string "LuaRules/Gadgets/unit_script.lua"]:429: bad argument #1 to 'sp_SetPieceVisibility' (number expected, got nil)

**Comment by yuritch** [comment]
I'll fix that once I find out why it happens. Basically the nebel rockets don't use ammo for some reason, they are supposed to use 1 per shot and the plane has 6, so only 6 rockets can be fired. Now they don't check ammo and go beyond 6, for which there are no model pieces.

**Comment by ashdnazg** [comment]
IIRC rockets in rocket planes don't use ammo but use the rockets on the model

**Comment by yuritch** [comment]
Hoko, I found no check for max rocket..n piece in the script. So what happens is that the plane fires 6 rockets fine, and then goes to fire 7th, and script errors because there is no piece rocket7 on the model.

**Comment by ashdnazg** [comment]
oh, I may have confused this with bombs

**Comment by ashdnazg** [comment]
no, not that either

**Comment by ashdnazg** [comment]
https://github.com/spring1944/spring1944/commit/440a88ea493d6036f78c93a7285678d785a8d46b
