### ISSUE TITLE
error while attacking with planes

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#171]
i attacked with ITAMC202 vs Yak9

[f=0004590] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_planefear.lua"]:119: attempt to perform arithmetic on local 'fuel' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/game_planefear.lua"]:119: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?
[f=0004605] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_planefear.lua"]:119: attempt to perform arithmetic on local 'fuel' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/game_planefear.lua"]:119: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?
[f=0004620] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/game_planefear.lua"]:119: attempt to perform arithmetic on local 'fuel' (a nil value)

**Comment by yuritch** [comment]
Was this in spring 101 or 102? Those versions dropped engine fuel, so now the scripts need to be redone with that in mind. Should not happen in 100 however.

**Comment by jal76** [comment]
i used 100, i tested newer engine later and didnt have them installed

**Comment by ashdnazg** [comment]
I've put the changes in fuel in master already, so that's the reason

**Comment by ashdnazg** [comment]
https://github.com/spring1944/spring1944/commit/440a88ea493d6036f78c93a7285678d785a8d46b
