### ISSUE TITLE
artillery sound

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#174]
artillery sound is wrong, you only can guess that something is shooting at you by explosions

**Comment by yuritch** [comment]
Does that mean you don't hear howitzer sounds from fog of war? Or you hear wrong sounds? Description is not very clear

**Comment by jal76** [comment]
its the explosion sound of the 105mm shell, wich sounds like 37mm

**Comment by yuritch** [comment]
Fixed by 6e2535ced6e8b44a8e4a49a0a0112739a055ef9b
