### ISSUE TITLE
flags got attacked

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#175]
my Daimler attack flag , other player reported that Hungarian tanks attacked flags too.

**Comment by ashdnazg** [comment]
https://github.com/spring1944/spring1944/commit/11455bc78d97675c2ec1608dd140166e9777dc30

**Comment by yuritch** [comment]
Fixed HE cannons targeting now (should affect all units with such weapons, including the Daimler).
Try d755349

**Comment by yuritch** [comment]
JAL confirms it's fixed with d755349. Reopen if not.
