### ISSUE TITLE
Infantry script error on 100.0 / 4573 (c827dea)

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#176]
This error was spammed to chat many times. Otherwise game went very smoothly this time. 

[f=0017025] [infantry script] Error: no fire transition change possible: prone_aim_mg prone germg42, 27223
[f=0017026] [infantry script] Error: animation error

**Comment by yuritch** [comment]
Supposedly fixed in 0cb4110ce48f5d62764e6a20fb27b0072dfc7f8d. Will reopen if not
