### ISSUE TITLE
infantry script error movetype

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#177]
[f=0032616] [unit_script.lua] Error: [string "scripts/infantry.lua"]:353: [SetMoveTypeData] unit 12202768 has incompatible movetype for °'Ÿ

happened in several games, some payers crash others not.

**Comment by jal76** [comment]
http://pastebin.com/F4z4Etkh

**Comment by ashdnazg** [comment]
I need a replay

**Comment by buumi** [comment]
[There you are](http://replays.springrts.com/download/b360475792619199ede8dc8b9c97ee16/)

**Comment by buumi** [comment]
Infolog from my Windows machine where it seems to crash game every time. 
http://paste.springfiles.com/view/983f4446

**Comment by yuritch** [comment]
Happens when a deployable infantry (like a rusmaxim) is shot while being deployed.

**Comment by yuritch** [comment]
Fixed by 9354b200656da51c64e1e927af960d0c9422cd5b
