### ISSUE TITLE
Paratroopers invulnerable at air

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#180]
During the drop you can't kill paratroopers, tried with inf, AA and fighters, none worked

**Comment by Lowdive** [comment]
:o, infinite mischief x2!

On Sat, Jun 18, 2016 at 1:28 PM, buumi <notifications@github.com> wrote:

> During the drop you can't kill paratroopers, tried with inf, AA and
> fighters, none worked
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spring1944/spring1944/issues/180>, or mute the thread
> <https://github.com/notifications/unsubscribe/AFWtfadYZmUrHGU2fo1O6-ZGcgR3jCYKks5qNDjggaJpZM4I5AVC>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by yuritch** [comment]
Can't reproduce.

Test: dropped 2 scquads over a starting SWE base. None reached the ground - 2 AA guns killed all in the air.

**Comment by yuritch** [comment]
Seems to be fixed by 567c2c30dede8b1091a71145e2d9bc2446a55e00
