### ISSUE TITLE
Skytrain flying too low

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#184]
Skytrain gets targetted by normal AA guns thus getting killed already at front because it's so slow. It used to fly high enough to avoid AA fire

**Comment by buumi** [comment]
Still happens on 4748-e5dd41a

**Comment by buumi** [comment]
Seems to be still happening even after fixes a few weeks ago. AA still kills and scares Skytrain away from the map without it dropping troops.

**Comment by jal76** [comment]
almost fixed
