### ISSUE TITLE
aircraft issue

### ISSUE THREAD

**Issue by idodoappo** [spring1944/spring1944#185]
when i build aircraft they dont come i have the latest version

**Comment by FLOZi** [comment]
Building just stockpiles them ready to deploy, you have to click on the stockpiled icon and issue an order on the map for them to arrive.

**Comment by idodoappo** [comment]
where's the stockpiled icon?

**Comment by Lowdive** [comment]
when you select a radar facility you see two option icons for each plane in the building menu, the upper icon is for building the plane and the second icon (that is lower) is for ordering the plane to come to battle once it's built

**Comment by idodoappo** [comment]
i do that but the plane is not moving

**Comment by Vancer2** [comment]
Click the icon that says Ready and then click a point on the map

**Comment by FLOZi** [comment]
http://i.imgur.com/bygvb6C.png The top set of buildpics which say Ready, as Vancer said.

**Comment by idodoappo** [comment]
i produce the plane but when its finished it just does nothing i dont see the ready icons

**Comment by FLOZi** [comment]
Please post your infolog.txt, should be next to spring.exe

**Comment by idodoappo** [comment]
https://www.mediafire.com/?qznaiwet9non8de

**Comment by FLOZi** [comment]
Problem is due to playing S44 v2.0 on Spring 103. I suggest using SpringLobby's 'Download Archive' tool (enter game:s44:test) to get the latest development version of S44.

**Comment by idodoappo** [comment]
ok i download the test file but it gives me XTA

**Comment by FLOZi** [comment]
I'm afraid you must have done something wrong, if you entered game:s44:test it will have given you the latest version of s44 and not possibly anything else.

**Comment by yuritch** [comment]
Try joining one of the test games - there usually is an autohost with them. SpringLobby will try to download it then, this way you won't get XTA instead.

You don't have to play in that battleroom, just join it and then you can leave (download will still be working in the background).

**Comment by yuritch** [comment]
Does not seem to be relevant anymore.
