### ISSUE TITLE
Game crash on S44 Test Version 4750-1ee74d4 with unit in boat

### ISSUE THREAD

**Issue by Vancer2** [spring1944/spring1944#186]
Game crashes when moving unit inside a pontoon boat. (Only played with Germany)

**Comment by yuritch** [comment]
Does not crash for me. Any details? Such as which map that was, which unit was being loaded.
I tried transporting Pumas with german pontoon rafts and there were no crashes.

**Comment by Vancer2** [comment]
IT was a problem with me with the water shaders. I never had a problem before. FLozi instructed me to type /water 0 and it fixed it.
