### ISSUE TITLE
Commando's smoke grenade consumes satchel charges

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#189]
As it only has two satchel charges at max that's quite problematic. I've had multiple times this happening, having only one satchel charge left, throwing smoke grenade and it's out of ammo.

**Comment by buumi** [comment]
It seems even Sten uses ammo from commando making it very broken

**Comment by yuritch** [comment]
Fixed in fe160da8a313804f87c70fd6ab3b961c00b547e2
