### ISSUE TITLE
JAgdpanther moves around while firing in hold position mode

### ISSUE THREAD

**Issue by Vancer2** [spring1944/spring1944#190]
While the Jagdpanther is firing and set to hold position it will move about. This is in test version 4750-1ee74d4

**Comment by yuritch** [comment]
Was it given a manual fire order? Was it just turning in place?
(we do not directly control movement in this case, so if there is an issie, it's an engine one)

**Comment by sanguinariojoe** [comment]
It seems the issue has been abandoned...
