### ISSUE TITLE
New interface

### ISSUE THREAD

**Issue by frju365** [spring1944/spring1944#197]
hi,
It's not a bug but an improvement and a feedback. I find on my point of view the graphic interface a bit "old"(Ammunition bar...). Perhaps you can fork gadget from the BA interface.
Thanks,
frju365

**Comment by frju365** [comment]
Nobody answers... and moreover pepeAmpere is doing a new interface. So, I close it.

**Comment by sanguinariojoe** [comment]
I comment about that... Theoretically Pepe's fork has a new buggy UI, maybe we can take a look...
