### ISSUE TITLE
[Balance] AT inf aim too slow

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#199]
Very often it's possible to drive with vehicles into AT inf groups and kill all the AT inf as they aim so slow vehicle kills them first. It's even worse because of Spring issue where you can't really flank autocannon vehicles with infantry. Could AT inf aim speed be increased / fixed?

**Comment by FLOZi** [comment]
It's caused by the ReAim function in scripts/Infantry.lua, but I'm not sure what the purpose of that function is for other infantry units. Calling liberal arts major @kanatohodets to explain coding to BSc Comp Sci me.

**Comment by sanguinariojoe** [comment]
OK. I'll take a look

**Comment by FLOZi** [comment]
Actually current anims are written by @ashdnazg they replaced Nemo's iteration.

**Comment by ashdnazg** [comment]
aiming is most likely configurable I think?

**Comment by ashdnazg** [comment]
it's not: https://github.com/spring1944/spring1944/blob/master/scripts/Infantry.lua#L197
Anyway, if you want them to aim faster that's where you change it.
