### ISSUE TITLE
Engineer Reclaim Bug  ---- Renew

### ISSUE THREAD

**Issue by frju365** [spring1944/spring1944#200]
I report this bug because I want to specify the description of this bug. Problem: the engineer reclaims, but after moving he doesn't reclaim anymore. If we renew the reclaim command, he reclaims again. Conclusion : it's not a problem of distance or of Reclaim time. 

I've tried with 102.0 engine with  Tangerine map: it is the same problem. Tangerine is unplayable if this reclaim bug is not fixed. JAL thinks that  the problem is similar to the "Boat stuck" bug.
I think a function in the infantry.lua  must be written to renew the command automatically after the eng moves or just  specify that if the eng aims at a tree during ... seconds, the tree must  disappear.

Seems similar to #105 bug.
 
Edit: I have not write that it doesn't happens with "eng vehicles" (reclaim works fine with vehicles).
Edit2: I've tested with 103 engine and s44 2.0 and reclaim command works for eng inf.

**Comment by specing** [comment]
I suppose a valid first step to getting this resolved would be adding a reclaim progress indicator of some sort.

**Comment by buumi** [comment]
Did some bisecting and it seems commit that broke it was
#c7c141c06a148d14b4a5b9db93c8f2bbfccfc1c4

**Comment by sanguinariojoe** [comment]
I did that:
https://github.com/spring1944/spring1944/pull/207

Tested a bit and seems to work
