### ISSUE TITLE
License of S44

### ISSUE THREAD

**Issue by frju365** [spring1944/spring1944#201]
hi,
I wanted to translate the game into French but I wanted to license my work under the CC-BY-NC common license(Creative Commons Attribution-NonCommercial 4.0 International License) because I don't want my translation to become in the future a commercial thing. The whole Spring1944 code can perhaps change license too. 
Moreover because of the creation of a lobby(S44NotaLobby), Spring1944 must be clear, I think, about  the license it uses.
Thanks,
frju365

**Comment by ashdnazg** [comment]
the code can't be NC because it has to be GPL compliant. the assets are CC By NC unless stated otherwise IIRC.
Anyway, translation can be CC by NC, this is entirely ok.

**Comment by kanatohodets** [comment]
https://github.com/spring1944/spring1944/blob/master/docs/License.txt -- ashdnazg is correct. Lua is all GPL (v2), everything else is CC-BY-NC.
