### ISSUE TITLE
Missing rank graphics for ITA, JPN, HUN and SWE factions

### ISSUE THREAD

**Issue by specing** [spring1944/spring1944#202]
On a side note, does representing experience with ranks make sense?

**Comment by shibumi** [comment]
I have japanese ranks.. where shall I include them into the project?

**Comment by specing** [comment]
They are rendered (not images) in LuaUI/Widgets/gui_s44_ranks.lua

**Comment by shibumi** [comment]
ok damn.. now idea how to include them then.. Here is a full list of japanese ranks:

https://en.wikipedia.org/wiki/Army_ranks_of_the_Japanese_Empire_during_World_War_II

**Comment by sanguinariojoe** [comment]
OK, I'll do that... Pretty annoying actually, we should think an easier way to do that

**Comment by sanguinariojoe** [comment]
I created a related PR. In that PR the JPN faction has been added, and more specifically [in this commit](https://github.com/spring1944/spring1944/pull/372/commits/171410b99fe654e8cb1c5b995921006d90aaf09b).

**Comment by sanguinariojoe** [comment]
The PR has been merged, so I assign the issue back to @specing . Who is responsible of adding the faction ranks?

**Comment by sanguinariojoe** [comment]
- [ ] ITA
 - [X] JPN
 - [ ] HUN
 - [ ] SWE
