### ISSUE TITLE
Ingame faction picker widget

### ISSUE THREAD

**Issue by specing** [spring1944/spring1944#203]
My proposal is something of circular design, random at the top, axis (4) grouped on one side, allies (3) on the other and neutral (swe) at the bottom.

**Comment by sanguinariojoe** [comment]
I joined random with neutral:
http://pasteboard.co/5InWcw2Dk.png

**Comment by specing** [comment]
@sanguinariojoe commit dc6ea74df42b70baae9291f42d318bf6670da3ff broke CRAIG, as in the later spawns with a random faction and does nothing.
