### ISSUE TITLE
improve landmine warning widget to show mine count and placement radius

### ISSUE THREAD

**Issue by specing** [spring1944/spring1944#204]
LuaUI/Widgets/gui_mineFieldNotify.lua

**Comment by specing** [comment]
Amazing: mines are placed not in a circle but in a square around placing point!

Should the command for unplacable mines be returned?

**Comment by sanguinariojoe** [comment]
Implementing this would be either useless or unfeasible. If you only states the initial number of mines, what the point? Adding land marks when they are consumed will be annoying, and so far cheating.

So I don't think we are doing that. For the time being I close the issue
