### ISSUE TITLE
can't move camera

### ISSUE THREAD

**Issue by Musickiller** [spring1944/spring1944#205]
Hello.

I have just installed Springlobby, downloaded Spring 1944 2.31, launched, and I can't move (or zoom) the camera.

Then I've downloaded other mods (Planet Defence for example) - there camera works OK.

It's one of the shortest bug reports I've ever written, but I really don't know what to add. I will continue testing and trying to find out what is happening exactly.

Technical data:
CPU: Intel Core 2 Duo 3GHz
Mem: 4GB
GPU: Nvidia 250GTS
Spring Lobby ver.: 0.255
Spring ver.: 103.0
Mod ver.: 2.31
Maps: several, all starting with "1944_"
Mode: Singleplayer with 1 C.R.A.I.G. bot

Regards,
Dmitry.

**Comment by buumi** [comment]
Hello.

It happens sometimes. Type into chat '/viewta' (with slash, without quotes) and it should work. So first enter to open chat and then /viewta. Another option is some key combo which I don't remember for sure now, might be Shift + F1 or F2.

**Comment by Musickiller** [comment]
So sorry - I still could not check it - no time at all =(

**Comment by sanguinariojoe** [comment]
This is, AFAIK, not a problem anymore
