### ISSUE TITLE
out of ammo issue with planes (maybe other stuff too)

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#206]
when MustangGA runs out of ammo (rockets), it cant use its MGs .

**Comment by buumi** [comment]
Are you sure about this? I tried it as I have been using Mustangs in the past without issues and it at least keeps attacking ground with MGs even after all the rockets are gone.

**Comment by jal76** [comment]
MGs worked vs infantry just not vs tanks and ground.
