### ISSUE TITLE
Update buildpic for SdKfz250/9

### ISSUE THREAD

**Issue by yuritch** [spring1944/spring1944#210]
GBR:
- [x] 4.5" Gun (Stationary & truck)
- [x] Glider Supplies
- [x] Jeep

GER:
- [x] Sdkfz 250/9
- [x] 10cm SK18 (Stationary & truck)
- [x] Kubel

HUN:
- [x] 31M 105mm (Stationary & truck)
- [x] Fiat 508
- [x] Fortified storage

ITA:
- [x] Cannone 105 32 (Stationary & truck)
- [x] Fiat 508

JPN:
-  [x] Kurogane
-  [x] Type-5 Na-To
-  [x] Type 92 10cm (Stationary & truck)

RUS:
-  [x] A-19 (Stationary & truck)
-  [x] Gaz 69
-  [x] Pr 165 Barge

SWE:
-  [x] Haubits M06 (Stationary & truck)
-  [x] Kanon 105 42 (Stationary & truck)
-  [x] Tank yard
-  [x] Volvo TPV

USA:
-  [x] Jeep
-  [x] M1 4.5in (Stationary & truck)

... and basically all ship turrets.

**Comment by yuritch** [comment]
New Na-To buildpic wanted as well

**Comment by sanguinariojoe** [comment]
So job done!
