### ISSUE TITLE
Original PNG images

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#211]
Regardless if you use them, providing the PNG images as well as the DDS images may be very convenient for Linux developers (where such format is hardly supported)

**Comment by yuritch** [comment]
Originals for most of my textures are svg actually (inkscape is a surprisingly great texturing tool)

**Comment by sanguinariojoe** [comment]
Even better! (I'm used to Inkscape, however I never applied it for texturing... interesting...)

Maybe, to let this repository cleaner as possible, we can create another one... spring1944_rsc or something like

**Comment by yuritch** [comment]
That will be 400+ megs (just checked my local files)

**Comment by FLOZi** [comment]
IMO add them to relevant folders in https://github.com/spring1944/models

**Comment by sanguinariojoe** [comment]
Thank you!

**Comment by yuritch** [comment]
I uploaded the svg for Na-To (the latest model) as a test. Please take a look.
This was done with inkscape 0.48, it renders differently in the new inkscape for some reason.

**Comment by sanguinariojoe** [comment]
It renders fine to me... I guess...
Inkscape 0.91

**Comment by sanguinariojoe** [comment]
@yuritch , would it be possible to get also the maps resources??

**Comment by yuritch** [comment]
@sanguinariojoe, what do you mean by map resources?

**Comment by sanguinariojoe** [comment]
All the stuff... Height map, textures, features...

**Comment by FLOZi** [comment]
Not likely they were made a long time ago mostly by Zverofaust and I doubt he kept them. Probably there exists some software that can recreate them from the compiled map files though.
