### ISSUE TITLE
[Naval series] Avoid micro to load and unload tanks at pontoons

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#213]
Deploying infantry at beach may be afordable, but deploying tanks (using pontoons) may become a bit painful, requiring significant micro stuff

I suggest some sort of automatization, such that the pontoons may be checking if a tank (close enough to it) wanna cross river/sea, consistently loading it (without user intervention).

Probably, the automatic unloading process may become more tricky... But a simple approach can be also carried out

---

P.S. If you confirm it is worth to be implemented, I can try to help

**Comment by specing** [comment]
Hmm, I seem to recall that BA/TA/etc had a transport helper widget that did this

**Comment by sanguinariojoe** [comment]
This si working much better now, right?
