### ISSUE TITLE
mobile artillery moves around while in hold position

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#221]
The GER, US and BRITISH mobile artillery is moving to the target although they should hold their position to fire.

**Comment by sanguinariojoe** [comment]
These kind of bugs are super annoying yet very hard to fix.

If for some reason they cannot find a good way to aim the enemy, they will roam towards the target like idiots. The behaviour changes constantly with the engine.

The latest times I played, I have not experienced much problems, so I'm closing this issue. Feel free to eventually open it again
