### ISSUE TITLE
1v1 shouldn't end when one player crashed

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#223]
1v1 shouldn't end when one player crashed.. There should be a timer (10m) for a rejoin until it will end and declare the winner.

**Comment by yuritch** [comment]
For the engine, there is no difference between a crash and a ragequit. How do differentiate? Or should it continue for 10 minutes with only one team left no matter what? :)

**Comment by ashdnazg** [comment]
ZK has a widget with "wait" and "win" buttons

**Comment by ashdnazg** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_chili_inactivity_win.lua
and
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/game_over.lua

**Comment by frju365** [comment]
I think, at least you need to give 1 minute after the player left to end the game. And add a setting to "pause" command , which can pause this end time. Is it possible ?

**Comment by shibumi** [comment]
@frju365 Well one minute is maybe a little bit less.. I would go for 5-10min. For booting up and everything..

**Comment by frju365** [comment]
@shibumi, you didn't get the point : ok, perhaps 2 minutes, but no more. Because the pause command (done by the other player) will stop the time, this 2 minutes. it's a bit like you let the other player controlling this 2 min. 10 is too much, because you can just pause and then you can wait the time you want for the other player. :)

**Comment by ashdnazg** [comment]
why are you guys bent on a "one size doesn't fit anyone" approach?
Letting the person who's still ingame decide whether to stop it and claim victory or to wait is the only option that makes sense.

**Comment by yuritch** [comment]
Tried to port Inactivity Win code with 0f6b1c0147c49af9986c5741cbab3f6cd76610f1

Looks like it should work (or maybe not)

**Comment by sanguinariojoe** [comment]
No further complains, so I'm closing the issue
