### ISSUE TITLE
Game crash while loading LuaRules

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#231]
It has been already discussed by the IRC channel

The crash is caused by a long loading time, while the engine is waiting for the first frame. In fact, the engine detects that the frame is taking too much time to be rendered, stopping and restarting the associated thread. Hence, the problem is not the crash, but the loading time itself.

The long loading time arises from the `LuaRules/Gadgets/gfx_customUnitShaders.lua` script, which is including `ModelMaterials/1_normalmapping.lua` and `ModelMaterials/2_features_normalmapping.lua`. Both subscripts should parse the models/features to get the normal maps:

```
(...)
for i, udef in pairs(UnitDefs) do
  if (udef.customParams.normaltex and VFS.FileExists(udef.customParams.normaltex)) then
    unitMaterials[udef.name] = {"normalMappedS3o", NORMALTEX = udef.customParams.normaltex}

  elseif (udef.model.type == "s3o") then
(...)
```

Unfortunately, the info at `udef.model` is not precomputed, but is requiring loading the whole model, which is in fact excessively hampering the loading process.

**Comment by sanguinariojoe** [comment]
Trying to workaround/bypass the `udef.model` by the usage of `udef.modelName` is not possible, since it has been declared deprecated (indeed calling such attribute it's not doing nothing but printing a warning)

**Comment by sanguinariojoe** [comment]
The problem can be partially fixed manually defining `customParams.normalTex` for each model, allowing to set `customParams.normalTex = ""` to the models without normal map.
That way the scripts can be modify to skip parsing a lot of models

**Comment by yuritch** [comment]
Idea: dump unitdefs from a running game and see which units have normalTex there, and then modify the defs.

**Comment by sanguinariojoe** [comment]
Sure... So wanna we try this fix?

**Comment by ashdnazg** [comment]
Note that modelName got undeprecated
https://github.com/spring/spring/blob/develop/doc/changelog.txt#L21

**Comment by sanguinariojoe** [comment]
Good to bear for the next version! Thanks!

**Comment by yuritch** [comment]
I created a new branch for spring104 compatibility changes, and this one is there. Load time is faster, and no stacktrace.

Con: not compatible with 103, so it has to be a separate branch.

**Comment by sanguinariojoe** [comment]
This is, AFAIK, fixed
