### ISSUE TITLE
logic error

### ISSUE THREAD

**Issue by politoxela** [spring1944/spring1944#235]
After initiating send me this message several times, could not navigate to taste and when I try to write inside the chat me appears much more 

>  logic error (/build/springlobby-snPMON/springlobby-0.237/src/gui/mainchattab.cpp:95 ): M_server_chat = 0

**Comment by Lowdive** [comment]
I'm not sure if this is something related to Spring:1944, because of the path in the error...
Did you mean to post this issue at the Springlobby github?: https://github.com/springlobby/springlobby/issues

**Comment by politoxela** [comment]
Thanks

**Comment by specing** [comment]
Where have you installed this springlobby from? Version 0.237 is outdated and this is probably why it is erroring out (protocol updates), latest is 0.255 or 0.256.

**Comment by politoxela** [comment]
I installed it from apt on ubuntu.

**Comment by specing** [comment]
Apparently 0.255 is available on later releases of ubuntu:
https://packages.ubuntu.com/search?keywords=springlobby&searchon=names&suite=all&section=all

Perhaps you can pull it from there?
