### ISSUE TITLE
light AT guns for US,GBR,HUN and GER

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#239]
medium AT guns are still a bit bad vs fast light vehicles , noticed 1vs1 with bad effect.
cheap light AT guns are needed in some games.

 i asked yuri a bit ago to make light AT guns for GER,US,HUN and GBR
 50mm,37mm,47mm,57mm AT guns in that order

**Comment by shibumi** [comment]
Fortified AT guns against heavy vehicles like IS-2, Panther, Koenigstiger, etc would be also nice

**Comment by sanguinariojoe** [comment]
I don't like the fortified AT ideas

@yuritch , are you planning to add those AT guns?

**Comment by yuritch** [comment]
I would prefer not to.

**Comment by sanguinariojoe** [comment]
So I'm closing the issue.

Anyway, all the balance is heavily affected by the new armour system, so probably new issues like this will be arising in the future
