### ISSUE TITLE
[naval series] Seamines

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#243]
Hello,
It would be nice to have seamines to mine areas on sea or do prevent landing operations from enemies.
I thought about 2 types of mines:

1. Coast mines like this: 
![](https://paste.archlinux.de/JKl9/)

2. real sea mines like this:

![](https://paste.archlinux.de/GLGg/)

**Comment by yuritch** [comment]
Not sure these have a place on our game scale.
I mean, you can just use land mines to protect the coats, and we use very few ships of the size which would really trigger the sea mines.

**Comment by sanguinariojoe** [comment]
I'm agree. I close the issue
