### ISSUE TITLE
Consistent 'aura' icons

### ISSUE THREAD

**Issue by FLOZi** [spring1944/spring1944#25]
We also need a set of icons to represent 

Supply: Inside supply & logistics available (currently a yellow +), Inside supply & insufficient logistics available (a grey +)

Ammo: Out of ammo (currently using old widget icon)

Suppression: Suppressed, Pinned (currently using old widget icon, I think a downwards arrow would be ideal, but colours need careful consideration as yellow implies things relating to ammo/logistics)

**Comment by sanguinariojoe** [comment]
I think the current UI is fair enough. Arrows usually denote motion. Yellow -> Red is a good way to indicate increasing danger. Moving to other color, like orange, will introduce more colors in the screen, not good at all.

I close this issue for the time being

**Comment by FLOZi** [comment]
The current UI is a shambles compared to similar system in MCL:

https://github.com/SpringMCLegacy/SpringMCLegacy/tree/master/bitmaps/icons
