### ISSUE TITLE
[JPN] Amphibious vehicles act on land like ships + buggy unloading

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#252]
Hello,
The amphibious vehicles of japan behave a little bit weird. They feel like ships on land and they don't have the `turn` option, available. They are light tanks. They should have. And the unloading is also buggy even on land.

**Comment by yuritch** [comment]
Ka-Mi light amphib tank has a Turn button.
Ka-Tsu amphib APC has not, but then the land based APCs don't have that either.
Looks consistent to me.

**Comment by sanguinariojoe** [comment]
Then I'm closing the issue
