### ISSUE TITLE
Add movingAccuracy to unit autodoc page

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#254]
As per requested by Joe I'm creating a wish request. https://gitlab.com/Spring1944/spring1944/wikis/units/germarder for example here instead of just inaccuracy would be nice to also have moving inaccuracy. That's something that matters when you're using vehicles. Adding issue here as the widget and page generator is part of this repository. Also "damage type" of a unit would be nice to have. It lists damages against different units but it doesn't tell which type each unit is.

**Comment by sanguinariojoe** [comment]
Fixed in e04f25a42868243ee95bdfcb3014bc45a58c26fc and 214e4212fadecb13507673b87cf58a8cb9d286de

Thanks! May someone close the issue?

**Comment by buumi** [comment]
Nice, thanks!

**Comment by ashdnazg** [comment]
It's not yet fixed in the main repo
