### ISSUE TITLE
Csaba and Toldi moves odd

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#258]
I noticed that csaba and Toldi move like turretless tank while aiming with AP.

**Comment by yuritch** [comment]
Csaba had an incorrect flare number for the coax mg, maybe that was causing the issue. Renamed the flare.

Don't see anything wrong with Toldi defs.

**Comment by jal76** [comment]
they still turn whole body , instead turret.

**Comment by sanguinariojoe** [comment]
I have checked it, they move right, turret and body are independent
