### ISSUE TITLE
Boat ammunition usage is inconsistent

### ISSUE THREAD

**Issue by FLOZi** [spring1944/spring1944#26]
e.g. Fairmile ammo is torpedos, which aren't used, so 6pdrs don't require ammo
Soviet BKA, Pr161 don't require ammo

**Comment by FLOZi** [comment]
This is resolved by merging comp ships, but the ammo stores of each turret probably need a once over, Nemo?

**Comment by kanatohodets** [comment]
I think this was resolved with #98
