### ISSUE TITLE
New Hungarian anti-tank weapon needed to deal with IS2 and higher

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#260]
maybe this http://ftr.wot-news.com/wp-content/uploads/2014/04/tra1.jpg
44M Buzogányvető rocket laucher on toldi II ,
there were also truckmounts .

**Comment by buumi** [comment]
I agree with that, Hungary has very hard time with heavy stuff. If we want to try keep all the factions capable for 1vs1 they could use some counter for heavies. 
@yuritch what do you think? We'd need a model for that if you don't disagree, that would be something we would need your help for

**Comment by yuritch** [comment]
We can make the truck version of the same rocket be able to fire (the model was intended to support this). Won't have great survivability difference vs an IS-2, Toldi armor is as good as none here.

**Comment by jal76** [comment]
My plan was to mix it in a TuranII tank rush.

**Comment by shibumi** [comment]
I just want to mention that JPN has much more difficulties with handling heavy stuff. So will JPN get a heavier TD as well?

**Comment by buumi** [comment]
Japan has 120mm tank, and Ho-Ro, which is rather cheap and good for sniping as it doesn't necessarily need sight. Also their AT plane works better. From my experience HUN has much tougher time.

**Comment by jal76** [comment]
https://steamuserimages-a.akamaihd.net/ugc/860610103265982592/2A26E1643E9842148660DCB4B48180D942049477/
I have a few ideas how to use this (smoke,mix it in a swarm).

**Comment by shibumi** [comment]
@buumi sorry, but ho-ro is a self-propelled gun, it's not a TD and you see this if you have a closer look at the armor of the ho-ro. Ho-ro can be easily sniped with tigers or other high-end tanks. Also, Ho-Ro is using HE and HE is much less effective than AP ammunition.

**Comment by FLOZi** [comment]
I would also prefer the truck version than 1-off Toldi version. Of course I am against paper units (hello, TAM) in general and quite comfortable with asymmetrical 1v1 balance of nations.

**Comment by shibumi** [comment]
Sure, but asymmetrical means also that a faction should be Nr 1 in at least one area, otherwise you can just remove the faction. If I think about GER or USSR, I will easily find an area where they are Nr 1, but if I think about JPN it's difficult. Same for Hun btw.

SWE: best infantry right now,
GER: Best fortifications, best heavy Tank
USSR: Best heavy TD
GBR: Best paratrooper (glider is so much better than paratroopers), Best light Vehicle (AEC)
USA: best airforce
JPN: ??
HUN: ??
ITA: got buffed through patches from JAL all the time :P

**Comment by yuritch** [comment]
> I would also prefer the truck version than 1-off Toldi version.

It just so happens we already have it mounted on a Krupp-Protze truck (transport mode for the launcher), and it should be able to fire from truck mode (directly backwards at least).

**Comment by FLOZi** [comment]
Awesome yuri <3 Sorry I don't know hun tree at all. Shibumi; let me be clear. I am 100% comfortable with sides being fundamentally underpowered compared to the big 4. Sweden was always meant to be so.

**Comment by sanguinariojoe** [comment]
@yuritch , is this fixed?

**Comment by yuritch** [comment]
It's not. The truck form of the launcher cannot shoot for some reason.

**Comment by sanguinariojoe** [comment]
@yuritch , I created the PR above, which should make the truck able to shot.

It is not consuming ammo with the second rocket, and it can aim everything (not just tanks). But probably you can fix that (I actually have not knowledge enough to do that)
