### ISSUE TITLE
Is unit_fortify.lua used?

### ISSUE THREAD

**Issue by PepeAmpere** [spring1944/spring1944#268]
@yuritch is unit_fortify.lua used at all? code_man says it was historically used by rusba64. Based on my full text searches I see no evidence of any usage right now. If its no longer used, i would like to remove this gadget.

**Comment by yuritch** [comment]
You can remove it, I never had time to finish that feature, and at some point it got removed from the only unit that had it anyway.

Just a note, there is a unit class TankShelter which is solely for this.

**Comment by sanguinariojoe** [comment]
I already removed it
