### ISSUE TITLE
Some factions should not be on the game

### ISSUE THREAD

**Issue by CitoplasmaX** [spring1944/spring1944#276]
Italy was not in the war since 1943.
Sweden never was in the war.

**Comment by FLOZi** [comment]
Artistic license much?

One can make an argument re: Italian involvement post 1943, however the addition of the Swedish side is simply a 'what-if' as they had a well established domestic armaments industry.

**Comment by PepeAmpere** [comment]
@CitoplasmaX noone argue about two facts you mentioned. But also I see no reason which both facts should imply that some "faction" should not be in game.

**Comment by shibumi** [comment]
We could better say which faction *should be* in the game. For example Finland!

**Comment by CitoplasmaX** [comment]
But the game is based on the final of the WWII

**Comment by ashdnazg** [comment]
The game is based on whatever the makers want :)

**Comment by CitoplasmaX** [comment]
How right you are and when I get mad at having to admit it.

**Comment by shibumi** [comment]
We should focus on the bugs instead.. can somebody close this issue?
