### ISSUE TITLE
The chat widget cannot hold the text

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#278]
Press Enter, start typing... After one or two keystrokes the message you are typing fly to the original position at the mid-bottom of the screen

**Comment by PepeAmpere** [comment]
which widget? screenshot and step by step repro would help

**Comment by sanguinariojoe** [comment]
step by step:

Press Enter, start typing... You'll notice fast whats going on

**Comment by sanguinariojoe** [comment]
https://pasteboard.co/H9KC3fO.png

**Comment by PepeAmpere** [comment]
obviously you have some other problems with your UI: e.g. the resource bar in the background

1) go to your `SpringData/LuaUI/configs`
2) delete all lua files with prefix `s44` and `ss44`
3) launch game again
4) follow your own repro
5) 👁 observe no error

**Comment by PepeAmpere** [comment]
btw i was asking for the repro steps because i was not able to reproduce your bug on clear revision of the game. Suggested format of repro is steps you above. Also mentioning commit where you see the issue and name of the widget you are using (e.g. i was not sure if you talk about old console or new console) is helping. Thats why its good to provide such info in any bug report.

**Comment by PepeAmpere** [comment]
btw arent you using both console widgets at the same time?

**Comment by sanguinariojoe** [comment]
Here we go! It seems that the game was reading configs from `$HOME/.config/spring` (so removing the stuff in `$HOME/.spring` did not helped)

**Comment by sanguinariojoe** [comment]
nope... just the new one

2018-02-28 17:28 GMT+01:00 PepeAmpere <notifications@github.com>:

**Comment by sanguinariojoe** [comment]
Happened again!

Shall I removed the config each time I play??

**Comment by PepeAmpere** [comment]
Just once should be enough. But I'll make sure default disabling of old widgets will happen in next UI improvement I work on. So there will be no doubts.

**Comment by sanguinariojoe** [comment]
I did not noticed this anymore... I'm closing that!
