### ISSUE TITLE
old UI should be optional

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#287]
I would like to have the old UI optional. I am fine with setting the new UI as default for new players, but I would like to have the old UI optional with all features. At the moment I managed the point, that I start the game and I have nearly all old UI elements. There are just a few things that I need to change manually to have the old UI (excluding the old esc-menu.. I can't get into it.. No idea what I need to enable for it).

When I start a new game I need to change over and over again the following things:

1. I need to enable/disable the nota map to get the old map back
2. I need to enable/disable the chillu console + Notachilli framework to get the old Chat function back

Things that still doesn't work after these changes are:

1. I can't get into esape menu with pressing shift+esc anymore..
2. When I use the *signal key* for marking something on the map I have a weird print screen afterwards. How can I disable it. I don't want that it pops up everytime when I use the signal key..

**Comment by PepeAmpere** [comment]
Hi @shibumi , nice description, thats how I like it.

Old UI compatibility there is hard to promise something - Ill try to make the life for old UI lovers easy but some changes may be too expensive.

Regarding the issues you have with buttons, there may be your lobby included as well. In both issues you describe Ill try to solve so it works no matter whats your original setup.

What would help me:

1) try get clean spring lobby and get s44
2) join to room with newUI and describe step by step what you do and what issues you observe - this will help to find the issue fast and fix it ASAP

**Comment by PepeAmpere** [comment]
@shibumi new updates in https://github.com/spring1944/spring1944/pull/292 - regarding oldUI it is all you asked for

**Comment by sanguinariojoe** [comment]
@shibumi please, confirm that the issue can be closed

**Comment by shibumi** [comment]
still not fixed. When I join a game, I need to enable/disable chilliUI and disable/enable ressource bars for getting chat widget.

**Comment by sanguinariojoe** [comment]
But have you tried @PepeAmpere "1944 Enable/Disable Old UI" widget?

> - F11
> - enable 1944 Enable/Disable Old UI
> - observe old UI
> 
> reverse
> 
> - F11
> - disable 1944 Enable/Disable Old UI
> - observe new UI

**Comment by PepeAmpere** [comment]
@shibumi was asked 6 times to clear his configs and he never responded he did that (I really wonder why :)) Based on such experience I assume there are wrong configs behind his problems.

**Comment by shibumi** [comment]
@PepeAmpere our last game was fine.. the chat widget loaded without issues. So issue can be closed.
