### ISSUE TITLE
GBR commando and SWE sniper has custom hitbox as well

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#293]
JAL please revert the custom hitbox for GBR commando and SWE sniper as well.
And please have a look at all other units.. I am sure there are more units with custom hitboxes...

**Comment by buumi** [comment]
ITA alpini too it seems

**Comment by shibumi** [comment]
USSR partisans has that as well

**Comment by shibumi** [comment]
US paratroopers has this as well: https://github.com/spring1944/spring1944/blob/14ddd7c940bb4643b0abe44749a3717b102454d6/units/us/infantry/USParatrooper.lua

**Comment by shibumi** [comment]
Here is the whole command with all affected classes: https://github.com/spring1944/spring1944/blob/bc617c9474e839423b38f05d326b0b8d527a9f85/units/ita/infantry/ITAInfantry.lua

**Comment by buumi** [comment]
Fixed in #294
