### ISSUE TITLE
[ITA] Italian AT-gun infantry behaves like sniper

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#298]
The Italian AT-gun infantry is way too strong. It oneshots enemy soldiers.. if you compare this to the russian AT gun infantry that makes only 1/3 damage it's way too strong and misses the reason for it. It should make more damage against light cars but don't kill infantry with one shot

**Comment by sanguinariojoe** [comment]
Well, maybe @yuritch can give some details... But it seems ITA AT is some sort of special unit, a sniper (great range, deadly for inf) without cloak ability, but with the possibility to damage cars

**Comment by yuritch** [comment]
In this case you want to ask JAL. If memory serves, he balanced that weapon :)

**Comment by shibumi** [comment]
I think this only applies to the upgraded 'elite' ITA units. (the one for 1900CP), although I still think there shouldn't be like sniper against infantry... opinions on this? @jal76

**Comment by shibumi** [comment]
@jal76 and why does UDSSR AT Rifle make 1/3 of the damage of the ITA AT rifle?
