### ISSUE TITLE
Singleplayer crash since update

### ISSUE THREAD

**Issue by lrinaldi** [spring1944/spring1944#300]
After the last springlobby update on Archlinux, I get random crashes on single player mode.
The game stop without any trace after few minutes.
I removed both .spring and .springlobby directories and completely uninstalled the game but the bug persists.

package : springlobby 0.264-1
game : 1944 3.00
bot : RAI 0.601

[infolog.txt](https://github.com/spring1944/spring1944/files/1887550/infolog.txt)

[RAIGlobal_LastGame.log](https://github.com/spring1944/spring1944/files/1887551/RAIGlobal_LastGame.log)

[springlobby.log](https://github.com/spring1944/spring1944/files/1887556/springlobby.log)

**Comment by lrinaldi** [comment]
I got these errors 
```
[f=-000001] Warning: [Init] GPU does not support either ARB or GLSL shaders for shadow rendering
[f=-000001] Error: [CreateProgramObject] Tried to create "treeNearDefShaderARB" a ARB shader program on hardware w/o support for it!
[f=-000001] Error: [CreateShaderObject] Tried to create a shader ("ARB/treeNS.vp") on hardware that does not support them!
[f=-000001] Error: [CreateProgramObject] Tried to create "DecalShaderARB" a ARB shader program on hardware w/o support for it!
[f=-000001] Error: [CreateProgramObject] Tried to create "DecalShaderGLSL" a GLSL shader program on hardware w/o support for it!
[f=-000001] Error: [CreateProgramObject] Tried to create "DecalShaderARB" a ARB shader program on hardware w/o support for it!
[f=-000001] Error: [CreateProgramObject] Tried to create "DecalShaderGLSL" a GLSL shader program on hardware w/o support for it!
[f=-000001] [LuaUI] Warning: Headers files aren't supported anymore use "require" instead!
[f=-000001] [Texture] Warning: [LoadAndCacheTexture] could not load texture "Spring unit" from model "objects3d/gen/flag.s3o"
[f=-000001] [Texture] Warning: [LoadAndCacheTexture] could not load texture "" from model "objects3d/jpnteke_build.s3o"
spring: src/intel/genxml/gen8_pack.h:66: __gen_uint: Assertion `v <= max' failed.
```

**Comment by PepeAmpere** [comment]
Check https://github.com/spring1944/spring1944/issues/286 and try suggested workaround

**Comment by specing** [comment]
Does springlobby crash or does spring/engine/game crash? Or do both crash? Or is there no crash? I see the SL log ends with a warning and no crash log. Similarly infolog has no "Fatal" in it and I can see that you mentioned to get at least 5 minutes into the running game.

RAI is unsupported and you are lucky it does not cause crashes on load. Only CRAIG and spammer are S44 AIs.

**Comment by lrinaldi** [comment]
springlobby did not crash at all, the game went full screen, I played several minutes and the game stopped, springlobby is still opened. I tried gdb on springlobby : no traces
I will try some graphical settings change and other bots and let you informed. (I just tried CRAIG and : same problem)
What I also noticed is that : GL renderer:  Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
in the infolog.txt, It should have been an NVIDIA card.

**Comment by lrinaldi** [comment]
Problem solved, my laptop uses Optimus technology, that means you have to switch the use of the nvidia graphics card to play 3d games, normally the integrated graphics chipset is used. I completely ignored it.

To solve the problem, you have to install bumblebee and run springlobby with the command:
`optirun springlobby`

The game is so far better now, no crash anymore.
If it can helps someone ...

Thank you for your replies

**Comment by specing** [comment]
Intel should work well on low settings. I believe only the supply ranges would not be visible. Hell, it even works on GMA4500HD, which is 10 years old at this point.

**Comment by lrinaldi** [comment]
It's still weird, it worked perfectly before the last update, without touching the nvidia gadget.

**Comment by sanguinariojoe** [comment]
Shall we close that?

**Comment by specing** [comment]
yes
