### ISSUE TITLE
NOTA shortcuts are confusing new players

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#301]
The NOTA shortcuts of the new UI are confusing new players that come from BA or other games. We should make sure to use the default spring shortcuts.. so F4 for showing flags etc... I had over 3 new players now and all are nearly quitting after being stucked in a camera view with F4

**Comment by sanguinariojoe** [comment]
+1

**Comment by shibumi** [comment]
@sanguinariojoe maybe we should delay a release with the new UI until it's bug free and ready?

**Comment by sanguinariojoe** [comment]
I already asked if we wanna make a release with the former UI... i.e. Setting the Old UI as the default one (not removing the new UI, of course)

**Comment by sanguinariojoe** [comment]
Several comments (just to feed the new UI/old UI discussion):

* The new UI is unstable in spring-103 (https://github.com/spring1944/spring1944/issues/286)
* The new UI will be hard to upgrade to spring-105, at first glance...
* We have problems with newbies coming from other spring games (https://github.com/spring1944/spring1944/issues/322)

That make me feel like moving back to the old UI for the time being is a good approach. Devs can always enable the new UI to test

**Comment by shibumi** [comment]
@sanguinariojoe good decision.. so maybe @PepeAmpere should revert his commits and move it to another branch?

**Comment by PepeAmpere** [comment]
This conversion brings nothing new, I just hear still the same arguments of the same people just described by different words. Keep it as it is or improve new UI. 

@shibumi please reduce your efforts which are not constructive
