### ISSUE TITLE
notAchili module version revert

### ISSUE THREAD

**Issue by PepeAmpere** [spring1944/spring1944#302]
@sanguinariojoe you reverted module commit in https://github.com/spring1944/spring1944/commit/f60be8f844ebb08093672fa156f03a94317ee16c so the license file was missing again in all next versions built by buildbot.

Watch out what you commit please (I suggest using git control system with GUI) because some license sensitive people can get mad.

I will revert it back.

**Comment by sanguinariojoe** [comment]
My bad! Sorry!
