### ISSUE TITLE
Unlimited ammo for tanks

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#308]
There seems to be a bug with supply mechanism. With it tanks can get ammo even when you're out of supply. 

Steps to reproduce:
 1. Get tank with 8 or 12 log consumption / shell. M15/42, Sherman or T-34/76 all work. 
 2. Get supply level to 13.2.
 3. See how supply goes down and gets refilled to 13.2 leading to infinite ammo.

**Comment by PepeAmpere** [comment]
https://springrts.com/wiki/Lua_MathExtra

**Comment by buumi** [comment]
So you'd prefer
```lua
local roundsPerTick = math.floor(maxAmmo * RELOAD_FREQUENCY / RELOAD_AVERAGE_DURATION + 0.5)
roundsPerTick = math.clamp(roundsPerTick, 1, math.floor(logisticsLevel / weaponCost))
```
?

**Comment by PepeAmpere** [comment]
isn't better

```
local roundsPerTick = math.round(maxAmmo * RELOAD_FREQUENCY / RELOAD_AVERAGE_DURATION)
```

in case of zero value, you have still fallback in code below

**Comment by buumi** [comment]
But that does not fix the issue? This gets rid of old workaround line above but roundsPerTick might still be > 1 leading to a situation where weaponCost * roundsPerTick below might fail if player has less supply available than needed for multiple rounds?

**Comment by sanguinariojoe** [comment]
I close the issue (reopen it just in case)
