### ISSUE TITLE
Tweaks directly pushed to master

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#312]
A discussion arised from the following commit:

https://github.com/spring1944/spring1944/commit/f67e7d460edb9872cd4ccc3fc6dbe8bdd5339e8b

@jal76  is used to pushed tweaks right to the master branch. In fact, we tacitly allowed him to do that... But it's worth to know if people is actually agree with that...

Indeed, the current system is based on letting @jal76 freely tweaked things, complaining just in case (by means of the chat/riot). The main benefits are:

1.- Efficiency: Nothing easier than getting JAL tweaking params to balance/improve the game.
2.- Last man standing policy: Since it is not actually affecting the development, but just the user experience, it's good that someone may take action in case of Quorum cannot be reached.

The main drawbacks are:

1.- Lack of control: @PepeAmpere intercepted the commit commented above, however, sometimes the commits are flying under the radar, even introducing some errors
2.- Frustration: When someone firmly disagree with something, but @jal76 apply his superpowers, can be very frustrating...

**Comment by sanguinariojoe** [comment]
Unless someone is suggesting a new model I like it, I'm supporting @jal76 to still pushing tweaks directly on master (eventually complaining).

**Comment by PepeAmpere** [comment]
As I said in https://github.com/spring1944/spring1944/commit/f67e7d460edb9872cd4ccc3fc6dbe8bdd5339e8b I'm ok with keeping the current situation (rights, commit approach, etc.) so JAL can keep his special position.

On the same place I would just expect he would stop use sneaky methods to get around my different opinion.
