### ISSUE TITLE
Japanese heavy transporter Ho-Ha too expensive

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#317]
Currently the japanese Ho-Ha cost 1100 Metal. This would be compared to other heavy transporters totally fine, but the Ho-Ha has no weapons. I am not sure if this is a bug or on purpose, but according to english wikipedia the Ho-Ha was equipped with 3 Type 97 Heavy MGs. https://en.wikipedia.org/wiki/Type_1_Ho-Ha

So can we either reduce the price for it for let's say 700? 200 more as standard transporter, because of better armour or we give them 3x Type 97 MGs.. maybe 2 at front and one at back. Or 1 at front and 1 at every side? no idea.. CC: @jal76

**Comment by sanguinariojoe** [comment]
+1 (either you wanna add weapon or decrease cost)

**Comment by buumi** [comment]
Same for [43.M Lehel](https://github.com/spring1944/spring1944/wiki/units.hun43mlehel) then. I don't mind any of three options (add weapon, decrease cost or leave as is).

**Comment by shibumi** [comment]
For Compare:
The german Halftrack costs 1100 as well and it has weapons: https://github.com/spring1944/spring1944/wiki/units.gersdkfz251

The US,UDSSR and GBR halftrack costs 1200 (with weapons)

The ITA Halftrack costs 1100 (with weapons)

The swedish halftrack costs 1100 and has no weapons as well
https://github.com/spring1944/spring1944/wiki/units.swetgbilm42

So I would suggest to either reduce the price for the JPN,Swedish and hungarian one or we add weaponry to it.

I also think that the british `Ram Kangaroo` is too cheap. It costs only 1200 and it was normally equipped with a MG as well. Would be nice to have a MG for it but have a price of 1700 for it because of big armour. (It's maybe too fast as well)

**Comment by jal76** [comment]
done
