### ISSUE TITLE
Sound Issues with openal 1.19

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#318]
It seems like an upgrade on `openal 1.19` on Arch linux breaks all audio for spring1944. With `openal 1.18` everything works fine. This is definitley a spring1944 issue.. all other games work fine.

**Comment by sanguinariojoe** [comment]
You mean other spring games, right?

**Comment by buumi** [comment]
For me it affected other Spring games too, or at least The Cursed.

**Comment by shibumi** [comment]
@sanguinariojoe yes. I have tested "The Cursed" and there it worked.

**Comment by sanguinariojoe** [comment]
I cannot find nothing special regarding sound in s44. Is it broken from the very beginning, or is the sound suddenly interrupted?

**Comment by sanguinariojoe** [comment]
Surprise! I found this error:

```
[f=-000001] [Sound] Error:   Initializing EFX failed!
[f=-000001] [Sound] Error: CSoundSource::CSoundSource: AL_OUT_OF_MEMORY (40965)
[f=-000001] [Sound] Warning: Your hardware/driver can not handle more than 0 soundsources
[f=-000001] [Sound] Error: CSoundSource::Stop: AL_INVALID_NAME (40961)
[f=-000001] [Sound] Error: CSoundSource::~CSoundSource: AL_INVALID_NAME (40961)
```

Only in spring-103...

**Comment by sanguinariojoe** [comment]
AFAIK this problem is not anymore (tested in Arch), so I'm closing the issue
