### ISSUE TITLE
Hungarian bombers won't drop bombs

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#319]
Hi,
I thought this issue has been fixed but mario, firedow and cargnelutti + me played a game on kiev. I played random, so I stuck with hungary. In the middle of the game I tried building bombers but 9/10 bomber squads refused to drop bombs.. so I bought nebelwerfer bombers.. they did a better job but still same problem sometimes.

CC: @jal76 @sanguinariojoe

**Comment by jal76** [comment]
fixed.
