### ISSUE TITLE
Give more gun elevation and depression to turretless armor

### ISSUE THREAD

**Issue by marioxcc** [spring1944/spring1944#324]
In maps with a rough terrain, turretless armor like the SU-76 often refuse to fire becuase they are in an incline and can not raise the gun enough. That effectively renders them useless when standing on a slope. Suggestion: give all armor unlimited gun elevation and depression, like tanks, with turretless vehicles having still limited traverse.

**Comment by Lowdive** [comment]
I agree, we shouldn't make a case for a whole game mechanic to get a fix
for a particular situation where a better placement was required instead.

**Comment by simonpuchert** [comment]
What @marioxcc might be hinting at is that some of the vehicles are way too restricted. If an actual slope has this kind of placement trickery, it is fine. However, e.g. the SU-76 can only deviate by 6° from its main direction, which makes placing them a delicate business in some maps.
For what it's worth, Russian Wikipedia (English W. doesn't say anything about that) states
"Углы ВН, град.: −3…+25" (elevation: -3° ... +25°)
"Углы ГН, град.: ±15" (traverse: ±15°),
which is more than the SU-100 (but that has 12.5° "freedom" in-game). Generally I suggest avoiding extremely restricted angles as they lead to problems like these and would certainly not be realistic (who would want an AFV that only works on a pan-flat surface).

**Comment by yuritch** [comment]
Well, that is one of the disadvantages self-propelled guns have compared to tanks.
The engine doesn't provide a direct way to restrict vertical aim separately from horizontal aim, what it can do is 'aim cone' which is the same angle on both axis. Restriction can be done via unit script, but that would be an unneeded complication, in my opinion.

**Comment by simonpuchert** [comment]
In that case, should the maxAngleDif of the SU-76 (and possibly other similarly restricted vehicles) be raised (12 -> 25, like the SU-100)? That would probably fix the problem without trivializing placement of tank destroyers in general.

**Comment by FLOZi** [comment]
http://sketchtoy.com/69016871

**Comment by FLOZi** [comment]
> In that case, should the maxAngleDif of the SU-76 (and possibly other similarly restricted vehicles) be raised (12 -> 25, like the SU-100)? That would probably fix the problem without trivializing placement of tank destroyers in general.

For sure SU-76 is set at just 12 right now compared to 15 for StuG, Wespe... makes quite a difference. SU-100 is bizarrely set to a huge 25 despite real world 8.

**Comment by sanguinariojoe** [comment]
It seems no further actions will be taken in this regards, so I'm closing the issue
