### ISSUE TITLE
Lobby Hangs

### ISSUE THREAD

**Issue by derestle-htwg** [spring1944/spring1944#340]
Hello, i noticed that the lobby freezes.
After changing sometimes the menu/submenues it is just frozen.
Example:
Starting , the opening settings, move a little bit around graphics, general, lobby... back and forth. not really changing options, but just opening the settings page.
then after 5 or 6 changes the application freezes.

I could avoid this Problem by setting the SOunds Volume to off in the Lobby settings.

Those are the errors i saw on the commandline which gave me the idea and where i think it is related.

Best regards

(notAlobby.run:13379): GLib-CRITICAL **: 03:07:13.800: Source ID 5 was not found when attempting to remove it

(notAlobby.run:13379): GLib-CRITICAL **: 03:07:13.800: Source ID 6 was not found when attempting to remove it

**Comment by PepeAmpere** [comment]
Hi @derestle-htwg, thank you for reporting your problem. It looks like that your report is quite specific but in case it is not big problem for you we would appreciate full report from lobby, which you can send us using the integrated report system.

Just go into `About` > `Send logs`. Btw here you can observe all data you send (so you are aware of what are you sending us about your computer and potentially you can just copy wanted segments here).

Regards

**Comment by sanguinariojoe** [comment]
Is this not a springlobby bug? @specing? If so, can you please reply and close this issue?

**Comment by sanguinariojoe** [comment]
OK, no news... no reply... I'm closing this
