### ISSUE TITLE
ALT-key for switching between ally and public chat doesn't work anymore

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#344]
In the latest build the alt-key for switching between ally and public chat doesn't work anymore..

**Comment by sanguinariojoe** [comment]
This problem [is actually related with the engine](https://github.com/spring/spring/blob/develop/rts/Game/UI/KeyBindings.cpp#L58).

With [the new UI](https://github.com/spring1944/spring1944/pull/368) the problem would come back. I'm closing this issue anyway
