### ISSUE TITLE
New UI still buggy

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#345]
The new/old UI switch is still buggy. When I join the game I need to 'enable/disable' new UI to get the old UI fully functional. This happens in every game. Therefore the player can't start playing directly, he first needs to set UI settings for every game.

**Comment by PepeAmpere** [comment]
Can you provide repro with clean setup?

**Comment by shibumi** [comment]
Sure, make sure you have a clean setup, then join a game (you will see the new UI), then enable the old UI (this will work fine). Then quit the game and join the next game (you will see that the old UI will spawn, but the minimap on the left will miss)

Also: Ally/public chat-Switch via alt-key doesn't work

**Comment by PepeAmpere** [comment]
@shibumi I was interested in repro - step by step - each step on new line :) - "how you think you get the clean setup", because that is what is not clear to me. Maybe I do the clean setup different way.

Also it would be useful to know which operation system you use.

**Comment by shibumi** [comment]
Operating System: Arch Linux
Clean Setup: Delete the `.spring` directory in your home directory

**Comment by PepeAmpere** [comment]
and how you install it?

**Comment by PepeAmpere** [comment]
can you be very specific in your steps?

**Comment by shibumi** [comment]
I installed springlobby via package manager and then I downloaded all necessary files (game + spring engine) via springlobby

**Comment by shibumi** [comment]
And Yes I talk about the current master HEAD

**Comment by shibumi** [comment]
@PepeAmpere any update on this? I think I have provided you enough details, the UI is still buggy, I get the same issues. The map doesn't load and I have to manually disable/enable old UI + the position of the chat box is not saved. I start spring in -safemode, and I have cleared the .spring directory. If you need more information feel free to ask me.

Besides this: I played with a lot newbies, and they all were not happy about the new UI.  It adds too much elements to the sight of view and decreases the actual view for the player + it changes shortcuts (especially TA and BA players get confused as hell).

Also @jal76 mentioned other issues like:

1. No possibility to give up in the new UI
2. No possibility to see what an upgrade would cost
3. More??

**Comment by sanguinariojoe** [comment]
[A new UI](https://github.com/spring1944/spring1944/pull/368) is coming. I'm not closing this issue yet

**Comment by shibumi** [comment]
@sanguinariojoe A new "new" UI? or are you talking about a fixed version of pepe?

**Comment by sanguinariojoe** [comment]
Nope, is a revamped one. Take a look to the link

**Comment by sanguinariojoe** [comment]
#368 is merged! So this issue is fixed... Of course new bugs will come... Feel free to complain then (opening new issues)
