### ISSUE TITLE
japanese tankettes get stucked in Light Vehicle Yard

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#350]
The japanese tankettes get stucked in light vehicle yard and make it unusable afterwards.

**Comment by sanguinariojoe** [comment]
spring 104?

**Comment by shibumi** [comment]
@sanguinariojoe yes spring 104

**Comment by jal76** [comment]
<JAL> i tested with newest engine 104.0.1-1370, when factory is placed the ground doesnt get terraformed , so sometimes units gets stuck , depends on terrain.

**Comment by FLOZi** [comment]
Problem confirmed. However, ground is terraformed when constructed (and with /give) seems the problem occurs if the yard is facing east or west, but not north or south.
