### ISSUE TITLE
Some infantry corpses are not cleaned up (LuaRules/Gadgets/game_corpseCleaner.lua).

### ISSUE THREAD

**Issue by simonpuchert** [spring1944/spring1944#351]
In particular, [ruspartisan_dead] and [ger_shoulderhit] are not removed, as they don't contain "soldier". I can see two possible solutions:

1. Change the names to contain "soldier".
2. Change the way infantry corpses (or possibly other decaying features) are defined. E.g., add another property ("decays") or use another existing property (the description contains "Dead").

**Comment by sanguinariojoe** [comment]
Way 1 seems less problematic

**Comment by simonpuchert** [comment]
Let's look for new names then. I propose
- "ruspartisan_dead" -> "ruspsoldier_dead" (not to be confused with "russoldier_dead"),
- "ger_shoulderhit" -> "gersoldier_shoulderhit" (if that's not too long).

You can easily find better names, but these should do the trick.

**Comment by sanguinariojoe** [comment]
I would say it is needed to change the unit name as well

**Comment by FLOZi** [comment]
3. Create OO defs for features and do it cleanly with a customparam
