### ISSUE TITLE
Remove auto-victory feature

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#353]
The auto-victory feature is pointless, we should remove it. It has destroyed multiple good games with good 'come-back' chance already. Can we finally remove this feature? I know that it's possible to set new options on the server side for it, but the options reset all the time and its difficult to balance them on multiple maps, especially big maps with small flag amount are vulnerable to this feature, because the game will end too early.

**Comment by PepeAmpere** [comment]
@shibumi If you repeat the same arguments 20 times for 21st time its nothing new.  What about moving the discussion to next point?

* Be constructive and e.g. propose turning the feature off in case map has less than e.g. flags. 
* Another constructive point which supports real discussion would be e.g. bringing list of maps which have problems or links to replays of games which were "ruined".
* Last, third constructive point, would be to propose e.g. conditional end-game which needs UI confirmation from "winning" side. If winning side wants to end the match after current end-game rule is satisfied, game is ended. If instant end is not triggered by winning side, they can continue as long they want in already decided game.

**Comment by PepeAmpere** [comment]
@shibumi Do not take me wrong: I would be happy to remove you frustration from the feature but I would be happy if you always give it thought and bring some ideas on table or provide some data before you start to write hate-report.

**Comment by shibumi** [comment]
@PepeAmpere That's the point. You want to keep the feature in the game, I want to remove it, because I think it gives us no advantage. I mean what is the purpose of the feature? What problem do you want to solve with this feature?

I can give you the following summary from my side:

1. I want to decide when the game ends. Therefore I want to give up, when I feel like the game has ended. I don't want a feature that suddenly quits the game for me and destroys come-back plans or just fun on the game.
2. I am not the only one who told so. I remember @jal76 and @buumi sharing same thoughts about ending games too early too.
3. You asked for maps: Prokhorovka_1944, Eisenwald v1.0, Bandit_Plains_v1, 1944_Red_Planet, 1944_Prokhorovka_V2, 1944_Moro_River_V1, (Fairy Island?). These are the maps were the feature hurts at most, but for me it hurts in general on every map.

So to be constructive. I see two options:

1. We disable the feature and give control back to the player.
2. We modify the feature, that it displays a "do you want to give up dialog: yes / no" and the player is able to click on "no".

There are no other options in my opinion.

If you want to discuss how the game should end. Here are some ideas:

1. Destroying all enemy units

Too avoid endless games with people hiding scouts in the mountains. Here are some ideas:

1. Conquering all flags wins the game. (Could be interesting, sucks on some maps maybe. Players are forced to pick a starting location near/on a flag).
2. Game ends, when enemy has a certain amount of troops lost.
3. Game ends when enemy loses all buildings?
4. Game ends after a timer when all flags got conquered?

All of these options are better than the current solution in my opinion.

**Comment by sanguinariojoe** [comment]
In [this PR](https://github.com/spring1944/spring1944/pull/368) the auto-victory is drop, cause it was wrongly convoluted with the NOTA GUI.

Afterwards @PepeAmpere may create a pull request to ask for it get included again, so we can further discuss.

I'm not closing until [the PR](https://github.com/spring1944/spring1944/pull/368) is merged

**Comment by shibumi** [comment]
@sanguinariojoe Thanks! Auto-victory was really awful in 90% of the cases.. and the rest 10% of cases were actually quite funny searching some lone wulfs in the forests :D

**Comment by sanguinariojoe** [comment]
After merging #368, this should be fixed. Feel free to open a new issue otehrwise
