### ISSUE TITLE
Loading a tank back

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#354]
In engine 104+ i loaded a tank back to boat-transport and the game crashed .
https://justpaste.it/27dw2

**Comment by FLOZi** [comment]
Engine 1408, I had many crashes with transports before switching to 1510. Do you recall which boat and tank it was? Map is Downpour 1.1. If I can't reproduce in 1510 I'll close this as we can't run the stacktrace anyway.

**Comment by jal76** [comment]
it happened to 2 times, 1 time with italian, another with british tank transport

**Comment by FLOZi** [comment]
Can't replicate on 1510 with either itamz or gbrlct, closing for now.
