### ISSUE TITLE
composite units turrets ignore onlyTargetCategory

### ISSUE THREAD

**Issue by jal76** [spring1944/spring1944#356]
I tried to make the british landingsupportboat to aim landunits only with smokemortar , that didnt work , now it is 44M Buzogányvető the same : it shouldnt be able to attack infantry, but it does.

**Comment by sanguinariojoe** [comment]
I discuss the 44M Buzogányvető case, but I would say a similar problem is considered in other units.

The `onlyTargetCategory` is an attribute of the weapon, for instance, the US M5 gun has the following weapon section:

```
	weapons = {
		[1] = { -- AP
			name				= "M7ap",
		},
	},
```

So we need to take a look to that weapon (https://github.com/spring1944/spring1944/blob/master/weapons/Armour/MediumGun.lua#L220):

```
local M7AP = MediumAP:New(M7, true):New{
  weaponVelocity     = 1674, 
  customparams = {
    armor_penetration_1000m = 81,
    armor_penetration_100m  = 100,
  },
  damage = {
    default            = 2646,
  },
}
```

So we finally need to check the `MediumAP`,  (https://github.com/spring1944/spring1944/blob/master/BaseClasses/Weapons/Cannon.lua#L2)

```
local AP = Weapon:New{
	canattackground    = false,
	colormap           = "ap_colormap.png",
	impactonly         = true,
	name               = "AP Shell",
	soundHitDry        = "GEN_Explo_1",
	customparams = {
		damagetype         = "kinetic",
		onlytargetcategory = "SOFTVEH OPENVEH HARDVEH SHIP LARGESHIP TURRET",
		badtargetcategory  = "SOFTVEH",
	},  
}

...

local MediumAP = AP:New{ -- LightMedium & Medium
	explosionGenerator = "custom:AP_Medium",
}
```

So `onlytargetcategory` is a weapon attribute inside `customparams` of the weapon, NOT THE UNIT.

However, https://github.com/spring1944/spring1944/blob/master/units/hun/guns/HUN44MBuzoganyveto.lua#L11 defines it as a unit attribute (inside the weapon section).

2 possible solutions:

* Set it inside `customparams` (all attribute names in lower)
* Set it inside the weapon, not the unit

**Comment by FLOZi** [comment]
Infact it is a unitdef tag in the weapons table, as it has been set ( https://springrts.com/wiki/Gamedev:UnitDefs#onlyTargetCategory ) however S44 does some magic in one of the pre/post files to set it for each unit based on the customparam in the weapon, as typically a weapon has a fixed role and ergo fixed targets. Probably that magic is overwriting the one set in the unitdef. I will investigate and decide on best solution.
