### ISSUE TITLE
Wiki Generation Widget Needs Updating For Sloped Armour

### ISSUE THREAD

**Issue by FLOZi** [spring1944/spring1944#366]
We've gone from 4 armour values (front / side / rear / top) to 14 (hull front thickness, hull front slope, hull side thickness, hull side slope, hull side rear, hull side slope, hull top thickness... and repeat again for either turret or superstructure depending on the unit) Some units do have only the 7 hull measures e.g. APCs.

**Comment by sanguinariojoe** [comment]
PR for that:

https://github.com/spring1944/spring1944/pull/369

**Comment by sanguinariojoe** [comment]
BTW, I already updated the wiki. e.g. https://github.com/spring1944/spring1944/wiki/units.rust3476

**Comment by sanguinariojoe** [comment]
Merged

**Comment by FLOZi** [comment]
Awesome, thanks Joe
