### ISSUE TITLE
Move to CC-BY-SA

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#376]
Everything except lua scripts are licensed as Creative Commons BY-NC 3.0, which is not considered a free cultural license.

That has a number of drawbacks. The most important, we cannot announce the game neither in free-software forums nor in commercial platforms. Actually commercial platforms are not that clear, but it is blocking some plans to announce the game. @specing can give more details.

I think moving to Creative Commons BY-SA 3.0 will solve many problems, and it is indeed a harmless change.

I'm pretty sure @FLOZi and @yuritch are "assets" copyright owners. I think any of you are entitled to change the license.

**Comment by ashdnazg** [comment]
That was asked before and declined.
The art made by Spiked and others was made knowing that it is released under CC by NC.
It is not possible nor (as far as I know) desirable to change that.

**Comment by sanguinariojoe** [comment]
Real bad... Such is live I guess

**Comment by ashdnazg** [comment]
🤷
