### ISSUE TITLE
New UI feedback

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#378]
* Chatbox users are not colored correctly. Everyone was just light yellow.
* JAL's name in chat was %[S44]JAL
* Would be nice to see total income one has. That is quite vital when planning strategy. E.g. "Can I spam tons of tanks" is hard to know when I just see that I have "+3.5" income?
* Feature request: it is nice that one can scale and move widgets. But they seem to break if you make e.g. long widgets wide. Allowing one to also change their shape from | |  to === would allow quite nicely building UI for one's own taste.

**Comment by buumi** [comment]
Chat crashed on game start on second game
```
[f=-000001] [widgets.lua] Error: false
[f=-000001] [widgets.lua] Error: Error in GameStart(): [string "LuaUI/Widgets/gui_s44_console.lua"]:158: attempt to index field '?' (a nil value)
[f=-000001] [widgets.lua] Error: Removed widget: 1944 Console
```

**Comment by sanguinariojoe** [comment]
I moved the chat crash to a different issue.

> Chatbox users are not colored correctly. Everyone was just light yellow.

Strange, I see colors right in the replay (https://storage.googleapis.com/s44-demos/20201010_205305_1944_Titan_104.0.1-1553-gd3c0012%20maintenance.sdfz). And apparently I'm not the only one, as far I see in the chat itself.
But probably there is something working oddly, I'm carefully checking it.

> JAL's name in chat was %[S44]JAL

I see `%[S44%]JAL`. Probably it is doing some weird scaping. I'm fixing that!

> Would be nice to see total income one has. That is quite vital when planning strategy. E.g. "Can I spam tons of tanks" is hard to know when I just see that I have "+3.5" income?

You mean see the income minus the consumption, right?

> Feature request: it is nice that one can scale and move widgets. But they seem to break if you make e.g. long widgets wide. Allowing one to also change their shape from | | to === would allow quite nicely building UI for one's own taste.

It can be done, I guess... Maybe is a bit hard to handle the scrollbars, but I can think something...

**Comment by buumi** [comment]
> Strange, I see colors right in the replay (https://storage.googleapis.com/s44-demos/20201010_205305_1944_Titan_104.0.1-1553-gd3c0012%20maintenance.sdfz). And apparently I'm not the only one, as far I see in the chat itself.
But probably there is something working oddly, I'm carefully checking it.

I also saw colors before I reset my LuaUI configs to get clean state to remove other issues I had. Marigold and Firedow also reported that they did not see colors (or rather, everyone was the same color). So I think there is something wonky.

> You mean see the income minus the consumption, right?
Mm yeah. Don't really mind how it's visible but I want total income visible somehow as that has affect on strategies one can take. Now it's only showing result of (total income - total consumption).

> It can be done, I guess... Maybe is a bit hard to handle the scrollbars, but I can think something...
Yeah understood. Just an idea since it would also fix my previous grief about selection bar being on right side of screen. Since after that everyone could pretty much build their own layout.. :)

**Comment by sanguinariojoe** [comment]
Github decided to auto close the issue, but it is not completely addressed yet... I reopen it

**Comment by sanguinariojoe** [comment]
- [X]  Chatbox users are not colored correctly. Everyone was just light yellow.
- [X]  JAL's name in chat was %[S44]JAL
- [X]  Would be nice to see total income one has.
- [ ]  Allowing one to also change their shape from | | to ===
- [ ]  Show all widgets in unlocked/customization mode

**Comment by sanguinariojoe** [comment]
OK, the [PR](https://github.com/spring1944/spring1944/pull/381) shall fix the problems, please check!

**Comment by sanguinariojoe** [comment]
OK, I merged, let's see in the next game

**Comment by sanguinariojoe** [comment]
Can we close this?

**Comment by buumi** [comment]
Yes, thanks!
