### ISSUE TITLE
FPS drop significantly when troops selected

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#386]
With new UI my FPS drops from 290 -> ~35 when I select starting troops. Tested with Japan and GBR. 5672-56bdb2e.

**Comment by buumi** [comment]
Disabling selection bar increases FPS back to ~210. Still quite a big drop but not nearly as bad as with selection bar.

**Comment by sanguinariojoe** [comment]
I have the problem! I'm looking for the smartest solution
