### ISSUE TITLE
Ally chat improvements

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#388]
So in the last game typing a: before message worked sometimes, sometimes not. Sometimes it just prepended that to message and published it to everyone. It also didn't persist and old shortcuts for toggling between ally chat and everyone chat didn't work anymore. I'd probably prefer having that shortcut back since pointing with mouse is really slow in the heat of battle. "Nice to have" improvement would also be different colour for ally chat messages.

**Comment by sanguinariojoe** [comment]
The old shortcut was removed by spring engine, not me:

https://github.com/spring/spring/blob/develop/rts/Game/UI/KeyBindings.cpp#L58

I can of course recover the old shortcuts, but then we are introducing confusing stuff for people coming from other games...

Regarding the a: prefix, I actually should think a bit... maybe is easier than I though

**Comment by buumi** [comment]
Hmm, really? Double-clicking <Alt> has always worked for me when typing message. In old ui it toggled between :a and empty prefix.

**Comment by sanguinariojoe** [comment]
Ok, the [PR](https://github.com/spring1944/spring1944/pull/389) above should fix the problems, except the Double-clicking `<Alt>` shortcut, which I have not been able to use even in my oldest s44 version (much before the new UI).

Can you describe such shortcut in detail?

**Comment by buumi** [comment]
Actually with clean install I made I couldn't get it to working anymore either.. So it must've been some old configuration I was still carrying with me. It worked so that you'd open chat message writing by hitting enter, and then you click Alt twice to switch to ally chat, once more to switch back to "All" chat and once more to toggle again ally chat and so on. 

Anyways, it's not important as long as there's some fast way to toggling between chats. :)
