### ISSUE TITLE
Spring default "Selected units" text visible with new UI

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#395]
At least for me on the bottom of screen there's still default Spring "Selected units" text that does not go that well with new UI. Could be removed (or closed if it's just my issue again..)

![kuva](https://user-images.githubusercontent.com/4021203/95974827-1fc8e780-0e1e-11eb-969d-6484f86e7ada.png)

**Comment by sanguinariojoe** [comment]
Yeah, I'm looking how to remove that, but I did not found the key yet...
