### ISSUE TITLE
Firing smoke shells not working on at least some SP-Artillery vehicles

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#400]
I don't remember if it's intentional or not that SP-artillery can't fire smoke shells but at least they have smoke shell toggle now. And setting that toggle to "Smoke-mode" prevents vehicle from firing at all. So there's bug one way or another. Happened yesterday with ITA Autocannone da 100/17.

**Comment by sanguinariojoe** [comment]
[It clearly has smoke shells](https://github.com/spring1944/spring1944/blob/master/units/ita/guns/ITAAutocannone100.lua#L13). AFAIK "SPArty" is not a complete unit definition, but a subclass is required. The Autocannone da 100/17 is defined as a SPArty:

`local ITAAutocannone100 = Truck:New(SPArty):New{`

While other SPArty-based units have always a subclass:

`local GERWespe = LightTank:New(SPArty):New(OpenTopped):New{`
`local JPNHoNiII = HoNiBase:New(SPArty):New(OpenTopped):New{`
`local GBRSexton = MediumTank:New(SPArty):New(OpenTopped):New{`
`local USM7Priest = MediumTank:New(SPArty):New(OpenTopped):New{`

So I would say a subclass for the trucks should be defined, which at least provides the `category` and the `customParams.damageGroup` ones.

@jal76 please, can you take care?

**Comment by jal76** [comment]
fixed
