### ISSUE TITLE
Unit orders are glitchy

### ISSUE THREAD

**Issue by Firedow** [spring1944/spring1944#414]
Now that we can make Fight command the default, some glitches came along
It seems that every order that switched automatically depending on a situation (i.e hovering over a enemy unit will not automatically switch to Attack, hovering engineers over a damaged vehicle/structure will not automatically switch to Repair) is now gone, they can still be switched manually however.
And i didnt find 'Clear path' for my engineers (might be just a one-off since i got some UI glitches last match [mostly made by me fondling around])

**Comment by sanguinariojoe** [comment]
Oh yeah! I'm idiot!

I know what is the problem and I'll fix that ASAP
