### ISSUE TITLE
CRAIG units running past/into enemy soldiers without attacking (Test - 5693)

### ISSUE THREAD

**Issue by Marigold4** [spring1944/spring1944#416]
Since the recent update, CRAIG sends infantry running past enemy soldiers. I encountered this behaviour whilst playing JPN and thought it might be a feature, as infantry where charging my frontline... Also, seemed my infantry would pass by enemies nearby, even in range, without stopping to attack when given attack command for the area.

![Runningsoldiers](https://user-images.githubusercontent.com/74651208/101232218-6fcc7800-3704-11eb-9c4a-51c8d2ec8980.jpg)

**Comment by sanguinariojoe** [comment]
TY! I noticed that too. No idea what is wrong yet.

Anyway, I am working on the AI (a BIG update will come), so probably I am fixing this meanwhile.
