### ISSUE TITLE
Lots of glitches last match 

### ISSUE THREAD

**Issue by Firedow** [spring1944/spring1944#422]
https://pastebin.pl/view/61293f32

i got a chunk of the errors from the infolog, hope it helps

So visually what me and Lowdive saw, was that infantry froze their animations, buildings were in the ground and when Marigold joined to spectate, we both lagged for a while

**Comment by sanguinariojoe** [comment]
@yuritch merged before it was ready :-p

**Comment by sanguinariojoe** [comment]
Just for feeding a bit, the error happens when the unit is transferred to GAIA. For some reason the unitID is becoming some sort of invalid
