### ISSUE TITLE
aircraft

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#43]
the range drop broke aircraft pretty badly. major issues are that interceptors can't intercept, and they frequently crash into the ground while making strafing runs. 

I'm likely going to crank their weapon range back up (no range adjust) along with AA weapons, then perhaps raise the cruiseAlt.

**Comment by kanatohodets** [comment]
update: they still kinda suck, but I don't want to heavily refactor them before merging sweden, since it'll cause really brutal merge conflicts.

**Comment by sanguinariojoe** [comment]
I don't think this is an issue anymore
