### ISSUE TITLE
New gun mechanics feedback

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#431]
So this is more of a feedback than bug or issue (except maybe 1st point)

- At the moment guns don't basically have a deploy time. Loading and unloading a gun happens instantenously and you can also move the truck as soon as gun is loaded. For now there's not much abuse of the system but I think with some practise it will be easy to abuse and avoid normal deploy time of guns.
- Moving guns is a lot of micro. It used to be bad but now it's much worse since you need to build truck separately and handle load/unload by yourself and also position gun manually with move commands **after** it has first unloaded. Before you could give a move command and press deploy and select facing.
- Should all guns be movable without truck at all? I think moving of some heavy howitzers by foot would be very tricky to do

**Comment by sanguinariojoe** [comment]
> At the moment guns don't basically have a deploy time. Loading and unloading a gun happens instantenously and you can also move the truck as soon as gun is loaded. For now there's not much abuse of the system but I think with some practise it will be easy to abuse and avoid normal deploy time of guns.

Uhm, the engine does not offer nothing straight forward, but probably we can manually some delays, I can think about that...

> Moving guns is a lot of micro. It used to be bad but now it's much worse since you need to build truck separately and handle load/unload by yourself and also position gun manually with move commands after it has first unloaded. Before you could give a move command and press deploy and select facing.

The AI has some sort of taxi service... Maybe we need something like?

> Should all guns be movable without truck at all? I think moving of some heavy howitzers by foot would be very tricky to do

There are 2 things to be tuned, the speed of each gun and the accuracy (deployed vs. undeployed). On top of that, deploying should require more time, and effectively increase the gun strenght

**Comment by sanguinariojoe** [comment]
This is related with #434

**Comment by sanguinariojoe** [comment]
For the time being I have created a taxi service [here](https://github.com/spring1944/spring1944/pull/436)

**Comment by jal76** [comment]
i got a idea that you can produce towed guns like in the old times , but only until 1st deploy then you get refund for truck and it is like now.

**Comment by jal76** [comment]
Guns , except pack guns, shouldn't shoot undeployed .
Also , while deploying , the shooting arc should be select able .

**Comment by sanguinariojoe** [comment]
> i got a idea that you can produce towed guns like in the old times , but only until 1st deploy then you get refund for truck and it is like now.

There is not refund, but basically this is what will happens from now on

> Guns , except pack guns, shouldn't shoot undeployed .
Done

> Also , while deploying , the shooting arc should be select able .
No way, because you can cheat using that to instantaneously turn the gun
