### ISSUE TITLE
No trucks for rus at the beggining (DON'T MERGE YET)

### ISSUE THREAD

**Issue by sanguinariojoe** [spring1944/spring1944#434]
I never liked rus can select the starting pos, even at the risk of loosing everything. If a guy try to get a too advanced position and success, then he has a critical advantage. If he fails, the game is ruined in 2 minutes...

This problem is of course much worse now that there are no towed guns to counter rus players. The easiest solution is removing the initial trucks.

**Comment by sanguinariojoe** [comment]
Possible alternatives:

- No trucks for RUS
- Trucks for everyone
- AT vehicles for everyone (which one each faction?)

**Comment by buumi** [comment]
I'd prefer that we keep Soviets unique in a sense that they have slow start but chance to pick their strongpoint position. From that PoV AT vehicle would be best option for now, but I'm not sure every faction has something suitable at the moment? I mean giving something like Daimler could be quite OP as well..

**Comment by yuritch** [comment]
The starting trucks were needed exactly to provide that early expansion. Keep in mind that Soviet inf are many times worse at capping than anyone else, so just sending the inf in all directions is not a viable idea, and retaking anything taken by enemy is sloooow.
The 3 starting commissars seem like the better cappers, but you have to build a barracks with something, too, unlike the other factions. And, while that is going on, you don't have any unit production.

**Comment by jal76** [comment]
Let them start with deployed trucks, that will give the other side a bit more time to prepare.

**Comment by sanguinariojoe** [comment]
> The starting trucks were needed exactly to provide that early expansion. Keep in mind that Soviet inf are many times worse at capping than anyone else, so just sending the inf in all directions is not a viable idea, and retaking anything taken by enemy is sloooow.

Yeah, but it should be avoided they can take a position too close to the enemy starting point, so it is effectively blocking the enemy to get resources.

> Let them start with deployed trucks, that will give the other side a bit more time to prepare.

I added it to the list, but I don't know if those seconds will be enough to effectively change things. Maybe is a good solution!
