### ISSUE TITLE
S44 on latest 'develop' engine ?

### ISSUE THREAD

**Issue by mfld-fr** [spring1944/spring1944#463]
Hello, today S44 is running on engine 105.0 (+ patches), but it looks like many commits were made in the `develop` branch for the future 106.0. I tried to run S44 on the `develop` latest, but it fails to start after displaying the map, reporting some API breaks in the logs, starting with removed `gl.CreateList()`. Any idea of what to put in replacement of this API to make the game to run again ?

**Comment by mfld-fr** [comment]
[infolog.txt](https://github.com/spring1944/spring1944/files/7798307/infolog.txt)

**Comment by yuritch** [comment]
Seems like the 'development' branch of the spring engine is not really where the engine development is happening now. So it's not compatible with any of the major projects, and the devs don't even expect it to be.

**Comment by mfld-fr** [comment]
So I understand porting S44 on that branch is irrelevant considering the development current context. Thanks for the reply !
