### ISSUE TITLE
transparent unit

### ISSUE THREAD

**Issue by pxsxs** [spring1944/spring1944#470]
sometimes some units look like this:

https://imgur.com/a/P9jb1uB

Game version: test-5715
Engine version: 105.0

**Comment by segatrade** [comment]
Screenshot in very bad quality
Change in game settings to medium
Use Nvidia or turn off some amd settings like in manual

Also probably these parameters can help:
/DistDraw 200
/DistIcon 900

**Comment by pxsxs** [comment]
ok, when I open the image from my mobile it looks very bad quality, but if I open it from the pc it looks good.
Anyway I upload it again here.
![2022-08-08-233822_1920x1080_scrot](https://user-images.githubusercontent.com/64876933/183763384-bf490238-99d9-454c-885f-b61a903fda70.png)

I will try what you say

and just in case my specs are:

OS: Debian GNU/Linux bookworm/sid x86_64
Kernel: 5.18.0-16.2-liquorix-amd64
CPU: Intel i7-5500U (4) @ 2.400GHz
GPU: Intel HD Graphics 5500

**Comment by Lowdive** [comment]
There’s particular units that have a transparency effect to show that they are currently cloaked and invisible to the enemy.

Scouts and some AT infantry and such. I believe that could be what you are referring to.

**Comment by segatrade** [comment]
Yes. Seems everything is ok, just "Transperent can show that unit is hidden"
@Lowdive is correct
Especially USSR have a lot of hidden units

**Comment by pxsxs** [comment]
ok, thanks for the clarification to both of you :)
