### ISSUE TITLE
CRAIG doesn't move its units out of its base [build 3529, spring 98.0]

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#54]
I tried to play against normal and easy CRAIG on Titan. I tested to play against USSR, GER, UK and USA. All the factions started building barrack but they never moved their units out of their base. I could play 10 minutes yet all their forces were still on the base.

**Comment by kanatohodets** [comment]
yuri fixed this some time ago, Code_Man reported CRAIG to be working. yay!

**Comment by onkobu** [comment]
Issue still persists, S44Lobby 0.169, latest S44Main.sdd. Floodbank seems to work (CRAIG moving&fighting) but all others (incl. Titan) leave AI idling in its base. The fix described (removing the seed from LUA script) is there but ineffective.

**Comment by ashdnazg** [comment]
I suppose you mean springlobby and not S44lobby. (0.169 is extremely old btw)
What engine version did you use?

**Comment by onkobu** [comment]
I use the (ubuntu ppa-) repository mentioned on spring1944.net and copied the S44Lobby-info from the about dialog.
