### ISSUE TITLE
movingAccuracy doesn't work

### ISSUE THREAD

**Issue by Godde** [spring1944/spring1944#61]
MoveAccuracy doesn't work which should make units innaccurate when firing on the move.
A KingTiger is accurate even on the move currently even at max range.
I have tested really high values for MoveAccuracy to no effect.

**Comment by Lowdive** [comment]
Define: accurate
always hits target? or standard accuracy with some chance to miss anyways? Cause I tried some shermans on test dev rapid 3579 and missed some shots on the move, gonna watch replay

**Comment by Godde** [comment]
Actually its called MovingAccuracy. Actually it is Spring engine bug. Supposedly it will be fixed in the next engine version.
