### ISSUE TITLE
PTAB bomber can not use machineguns effectively

### ISSUE THREAD

**Issue by nyararan** [spring1944/spring1944#63]
Although it can fire them at a target occasionally, due to short range, low maneuverability, and what i assume is a preference to try and use bombs even while reloading, it will often simply fly over the target without ever firing.

tested on:
nuclear winter
dev-test-3600
vs null ai
attack ground, attack infantry, attack storage, attack deployed AT-gun

results: 
out of 6 PTAB bombers only 3 used machine guns against targets before running out of fuel
no bomber used machine guns more then once, or fired for longer then approximately 1 second

**Comment by ashdnazg** [comment]
I think this may be fixed in sweden

**Comment by yuritch** [comment]
Seems to not be relevant anymore
