### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by SoulRaiZor** [spring1944/spring1944#65]
Hi!

Game isnt that bad, but the chat is like from 1990s.
This needs some improvement with colors.
And if the text disappears i cant get him back to read.

Can u just copy the Widget from BA or any other mod?
All are better :D

**Comment by kanatohodets** [comment]
Hi SoulRaiZor,

We chatted about this on #s44, it is obviously a good thing to steal :). It isn't totally straightforward because the BA chat widget uses their custom UI framework (Red), so we'll have to do a bit of digging, but thanks for pointing this out.

**Comment by frju365** [comment]
fixed with https://github.com/spring1944/spring1944/pull/237

Can someone close this issue pls ?
