### ISSUE TITLE
Spectatormode

### ISSUE THREAD

**Issue by SoulRaiZor** [spring1944/spring1944#68]
Hey!
If i spec a game its not possible to switch between players to see their ressource bars.
I asked players, but no one knows how to do so.
We dont have that function yet?

**Comment by Lowdive** [comment]
you could use /SpecTeam 1 (or 2 or 3 or 0, etc)

On Mon, Feb 9, 2015 at 3:55 PM, SoulRaiZor <notifications@github.com> wrote:

> Hey!
> If i spec a game its not possible to switch between players to see their
> ressource bars.
> I asked players, but no one knows how to do so.
> We dont have that function yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring1944/spring1944/issues/68>.
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by ashdnazg** [comment]
Answered

**Comment by SoulRaiZor** [comment]
Thats too complex.
But a good way to keep new players away ;)

**Comment by kanatohodets** [comment]
Can't you just hit "1" for team 1, "2" for team 2, "3" for team 3, etc? That's what I've always done.

SoulRaiZor: is there a specific widget from another game you'd suggest for this? a better teamlist or something?

**Comment by SoulRaiZor** [comment]
I dont know its name, but in all other mods its working like this:

U choose an unit from team 1 - you get the info of team 1.
If u choose a unit from team 2 - you get the info of team 2 etc.
 
Iam sure i could find out the name of it in case u need it.
No big thing.

**Comment by kanatohodets** [comment]
Oh! That sounds like a really nice interface. Cool, I'll look for that. Thanks! Going to reopen so I don't forget about it.

**Comment by ashdnazg** [comment]
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_spectate_selected_team.lua

**Comment by ashdnazg** [comment]
Fixed in https://github.com/spring1944/spring1944/commit/3c10c795549a9f0603060d22341e087ff05d9cae
