### ISSUE TITLE
Commandos from Landing Zone start with 0 ammo

### ISSUE THREAD

**Issue by yuritch** [spring1944/spring1944#69]
As the title says - Commandos spawned from a Landing Zone (built by another commando) start with 0 ammo. Since this usually happens way behind enemy lines, there is nowhere to rearm from, meaning they cannot use satchels.

**Comment by ashdnazg** [comment]
Hmm, I should've thought about that.
As I see it they should spawn loaded, but the question is whether it should hit your supplies or not.

**Comment by kanatohodets** [comment]
they spawn with a little supply area now, so this is fixed.
