### ISSUE TITLE
List of tasks I've forgotten and need to be reminded of.

### ISSUE THREAD

**Issue by ashdnazg** [spring1944/spring1944#70]
Scripts:
- [x] ~~Engineer vehicles~~
- [x] ~~Katyushas~~
- [ ] Type 4 Mortar
- [x] ~~BA64 spinning spare wheel~~
- [x] ~~Transports~~
- [x] ~~Grenade throwing animation~~
- [x] ~~Planes~~
- [x] ~~Vehicle extra AA aiming~~
- [x] ~~Deployed units fear~~
- [x] ~~HMGs~~ (Thanks Nemo)
- [x] ~~Pack Howis~~
- [x] ~~Flip Japanese backward MGs~~ (Thanks Nemo)
- [x] ~~Amphibious vehicles~~
- [x] ~~Verify that HEAT works correctly~~ (Thanks Nemo)
- [x] ~~Boat yards!~~

Gadgets:
- [x] ~~Priority Toggle~~ - Works on dev engine
- [x] ~~If 99 is released, time costs of morphs need updating~~
- [x] ~~Give a hold fire toggle to undeployed guns, instead of defaulting to fire at will~~

Nice to Have:
- [ ] Make unloading fun, safe and working
- [ ] Move ~~armordefs~~ (Thanks Nemo) and shields into the unitdef, preferrably in base classes
- [x] ~~Base zeroing in on distance between last shot and target~~

**Comment by FLOZi** [comment]
Aircraft LUS?

HE/AP?MG Priority toggle?

**Comment by FLOZi** [comment]
I merged in the new Type 4 model. Should I take a crack at basic aircraft LUS?

**Comment by ashdnazg** [comment]
Thanks, I haven't even looked at them yet, so I'd say go for it.
