### ISSUE TITLE
Japanese AA scale

### ISSUE THREAD

**Issue by ashdnazg** [spring1944/spring1944#71]
Japanese stationary and mobile AA are the same gun, but they have different sizes:
![](https://dl.dropboxusercontent.com/u/204076271/scale.jpg)

**Comment by FLOZi** [comment]
There are many scaling problems, but we should try and prioritise such glaring ones first (i.e. same model in two places is different size)

**Comment by yuritch** [comment]
Model scale was worked on, this is probably resolved.
