### ISSUE TITLE
Random UI Things

### ISSUE THREAD

**Issue by ashdnazg** [spring1944/spring1944#73]
Add your favourites in the comments:
- Know your side before start if you picked random
- Show valid firing area
- Show gun penetration using colours overlayed on the fire circle
- When picking a unit have a picture (preferrably a rotating model) showing armour values, and a nice (prerendered) graph of penetration vs. distance.
- kmar wiki quotes as tips in load screen
- Firing arc ghosts, same as anti-rings

**Comment by kanatohodets** [comment]
* Display how much command was returned when planes leave the map. 

A scout plane sortie costs 1000 command to buy, but you get 650 of it back if it leaves the map without taking any damage. I think the lack of visibility on how economically efficient planes can be if used carefully is one of the reasons people scout rarely (or casually let the plane fly over AA).

**Comment by Lowdive** [comment]
* display how much command a flag is generating
* display how much command a building is spending

I picture this as a very nice and big white fill with black outline +1.3 or -20.1 on top of a building/flag

**Comment by ashdnazg** [comment]
Btw, Nemo I thought of a different system for planes, having planes "allocated" to you when you build them,
So if they stay alive, you can use them again after a cooldown for a small price/for free.
This will both make sense and deal with the issue of 10 wings returning at once

**Comment by SuperKmar** [comment]
NOTA has a thing that shows valid fireing area for units when you hold the Z key with the unit selected. Steal some code from there?

**Comment by sanguinariojoe** [comment]
I'm closing the issue due to the inactivity
