### ISSUE TITLE
OO Def Enhancements

### ISSUE THREAD

**Issue by FLOZi** [spring1944/spring1944#74]
- [x] :Append{ key = string value, ... } - (New: already takes a second optional argument to append only the 'name' key)
- [x] get rid of maxreversevelocity and just_post it to be 50%, 
- [x] remove weaponswithammo and make ammocost a per-weapondef attrib
- [x] i would maybe like to standardise turnrates a little 
- [x] brakerates seem standard and should be mvoed to baseclass, probablky accel could be too?
- [x] need to go through and add turret traverse rates in customparams
- [x] edit models so i can do script emit points my way and remove cegpieces
- [x] write actual speeds in kmph in defs, make lua calculate maxvelocity

**Comment by FLOZi** [comment]
Turn rates and acceleration & brakerate standardised somewhat - need a once over from Nemo and playtesting (hurrhurr minor stealth balance changes)

**Comment by FLOZi** [comment]
Added turret turnrates that I could find info for and defaulted to 24d/s. Probably should add slower rate for manual turrets (off the top of my head); Daimler, Puma, 250/9, T-60, T-70, Pz III, most jpn tanks...

**Comment by kanatohodets** [comment]
how's the model editing coming along? trying to do some issue gardening :)

**Comment by ashdnazg** [comment]
only planes remaining I think

**Comment by kanatohodets** [comment]
and now? all done as of 28e9cb0cc16?

**Comment by ashdnazg** [comment]
I'm closing this
