### ISSUE TITLE
Targeting Malfunction near Features

### ISSUE THREAD

**Issue by Lowdive** [spring1944/spring1944#75]
Godde and I were playing in bocage skirmish v4, and found out that:
If an infantryman tries to shoot at another infantryman behind or covered by a feature, say a tree for example, he won't be able to shoot at such target.
But the infantry man around or behind cover can and will shoot at the other unit.

Godde mentioned they can't target but they can shoot through features.

**Comment by kanatohodets** [comment]
what Godde said isn't quite true:

    local RifleClass = Weapon:New{
        ... stuff
        avoidFeature = true,
        avoidFriendly = false,
        collideFeature = true,
        collideFriendly = false,
        .... more stuff

and this is the same for SMGs and MGs. I suspect the problem has to do with a difference in the aiming/firing point for the unit behind cover (head/rifle) vs the point which is targeted (unit center, hip area). So a feature that covers the hips (or if the unit has clipped into a feature a bit) might prevent them from being shot at, but they'll happily shoot at others. That's my theory, at least.

**Comment by kanatohodets** [comment]
To add to this: bushes and other small features apparently also frequently muck up the aiming for our vehicles. I thought we had mitigated this with https://github.com/spring1944/spring1944/blob/master/gamedata/featuredefs_post.lua#L96 but evidently not as much as I thought. Worth checking to see if we can do anything more in featuredefs_post to make this less of an issue.
