### ISSUE TITLE
Idea: Fortified AT/AA/Howitzer/Fieldgun

### ISSUE THREAD

**Issue by shibumi** [spring1944/spring1944#80]
It would be nice to have fortified AT/AA/Howitzers/MG-nests like on the atlantik wall:
![](https://paste.archlinux.de/Mp6/)

I hope this will encourage people to use more engineers/mechanics on the frontline.

**Comment by sanguinariojoe** [comment]
This can be good for coastal guns, but we have not that a big ships, so I cannot see the point.

Since the issue is pretty old, and is not drawing attention, I'm closing it
