### ISSUE TITLE
'hold fire' is broken in sweden

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#89]
test: 

/give usm4a4sherman
set it to hold fire
/give 5 gbrkangaroo 1
watch the sherman fire and fire and fire. 

confirmed that this does not happen in master on spring 99-RC4

**Comment by kanatohodets** [comment]
tried with gbr HQ squads: with everyone on hold fire, the bren fires, rifles/smg only throw nades

**Comment by ashdnazg** [comment]
fixed in https://github.com/spring1944/spring1944/commit/04112bf2aa43cce5dcde986ce613e9af700771a7
