### ISSUE TITLE
HEAT shells occasionally do zero damage to front or rear armor

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#91]
This is a crazy one, but not too hard to reproduce with kangaroos as targets.

/give itasemovente47
/give gbrkangaroo 1
/give 15 gbrhqengineer 
set the HQ engineers to heal the roo, and turn it back and forth in HEAT range for the semovente. I found that probably two thirds or more of the shots fired at the front or rear of the roo did zero damage, despite penetrating. shots to side always dealt damage.

**Comment by kanatohodets** [comment]
turns out this is in master as well

**Comment by kanatohodets** [comment]
not only is it in master, it also happens in both 98 and 99-RC4.

**Comment by ashdnazg** [comment]
Following
https://github.com/spring1944/spring1944/commit/373138d00f2c75712672710d00ba9639d17693cd
can you test this on 98.0.1-577?

**Comment by ashdnazg** [comment]
actually fixed in:
https://github.com/spring1944/spring1944/commit/654e81fe7602e194bd0b0c7ac23f50d3e380aa3d
