### ISSUE TITLE
RFC: ditch wordpress/forum setup in favor of a static github page

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#93]
Chatted with hoko about a direction for the site, and I think it's at least worth considering ditching our current setup.

Basically: We have three big pieces of software run on our behalf by koshi: wordpress, mediawiki, and phpbb. All of them are famously insecure, and we hardly use them (other than the wiki, which I'll get to). 

I'm thinking about moving us to a static page hosted on github. Here's a quick breakdown of what we use in our current setup, and how we might replace it.
#### Wordpress --> static github project page

The few useful bits of content on the site (maps, media) can be moved over. For the other wordpress features -- we barely make use of wordpress for the authoring stuff, and the comments are mostly spam. Our image gallery is mostly dead links at this point, and changes so rarely that keeping screenshots in a branch of a repo would be perfectly fine. We're all sufficiently technical that writing newsposts by editing some markdown files and git push-ing is fine.
#### Mediawiki --> github wiki / curated content as part of the site

Mediawiki is probably the better wiki software, but porting the useful content wouldn't be very hard to do, since our wiki doesn't make extensive use of formatting, and it isn't themed in a meaningful way. 

That said, I think I would promote the best bits of the wiki to proper pages on the static site, so we can polish and curate and promote the best resources in a highly visible place. Other stuff can go into the github wiki, for assorted 'things users want to contribute'.
#### Forum --> ???

This might be the most contentious point -- giving up our dedicated forum. I can grab a backup from koshi, so the archive would still be available, but I think our forum is actually fairly damaging to our image. Our repo is really active (at the moment  :smiley:), but our forum is kind of a ghost town. One of the first things I do when checking out an open source game project is peek at the forums. No recent posts == no players, so I usually bail. 

I think we would be better served by drawing people directly into `#s44` using the IRC bridge by having a web-IRC thingy available from the static page, maybe in addition to some public logging or other persistent messaging. I suspect that between github issues and #s44, our communication needs are pretty much covered.

Thoughts?

**Comment by specing** [comment]
Done!

**Comment by sanguinariojoe** [comment]
In fact!

**Comment by frju365** [comment]
Perhaps time for me to leave definitely spring1944 community. Thanks for your work !
