### ISSUE TITLE
create a LoS shader with higher contrast than the default

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#94]
new engine release changes LoS to be a game-modifiable shader. the default is rather subtle, and hard to read on some map backgrounds. let's make one with higher contrast, potentially coming up with a better way to distinguish vehicle/infantry detection radii than 'white/green'.

**Comment by ashdnazg** [comment]
I think the shader's default colours changed, and now there is enough contrast

**Comment by kanatohodets** [comment]
yep, agree -- the default improved.
