### ISSUE TITLE
improve flag profiles so they can include the starting flag command value

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#97]
hoko's idea, and a really good one I think: flag map profiles would be way more useful and powerful if they also allowed us to change the resource distribution on the map, which would allow us to make use of maps with goofy resources but nice layouts/textures.

**Comment by kanatohodets** [comment]
done!

**Comment by ashdnazg** [comment]
Fantastic! https://github.com/spring1944/spring1944/commit/38f013473bef899c941e064f1f6d62458b4f1171
