### ISSUE TITLE
Sort out boats before release

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#98]
Some issues with boats that I'd like to resolve before cutting a release and merging sweden:

- [x] ~~fix children sometimes not being disabled after hitting min HP~~ -- minor bug in unit script, sorted out in 52b5ca5dad2471
- [x] https://github.com/spring1944/spring1944/issues/26 -- review ammo storage for children
- [x] ~~review ship hit volumes: some of them are quite inconsistent, which makes reproducing bugs with child turrets difficult.~~ -- made them all 1x1 footprint collision volumes; the 'reproducing bugs' thing was mostly the targeting issue solved by hoko adding canMove=true
- [x] check that _all_ ship turrets that should be vulnerable to suppression can be suppressed
- [x] ~~review HP values for hulls and turrets, following the mantra "hulls strong, turrets really weak"~~ -- hull HP --> 2x mass. turret HP --> like a halftrack/heavy vehicle.
- [x] ~~decide on a targeting scheme (children individually targetable, or not?) and stick to it. there's inconsistency here between ships~~ -- thanks hoko!
- [x] review child turret firing arcs (some can turn and clip through parent)
- [x] ~~make children appear in LoS at the same time as parents~~ - done in adf0d6b38b773e
- [x] fix Pr 161 rear turret not aiming (stuck inside hitvol?)
- [x] fix crash in compships
- [x] make turrets unselectable
- [x] ~~NOWEAPON for ship hulls~~ -- fixed BoatMother script to return false on AimWeapon. this seems like a pretty good middle ground.
- [x] buoy spawn should read from metalmap
- [x] remove torpedoes, evaluate whether some of the torpedo boats still have a role after that.
- [x] JPNSeta front main gun is inside the mother hit volume, so the projectile always explodes immediately
- [x] some landing craft (US for sure) leave a single infantryman floating in the yard after construction, which is weird and blocks further construction
- [x] GBR LCGM should start out -very- inaccurate, then gain parity with ground after beaching. right now it becomes the most accurate arty in the game after beaching and zeroing in.
- [x] GBR LCGM probably shouldn't have a 0.5 damage modifier after beaching; that's quite extreme.

Nice to have, not blockers:

- [x] smoke emission for damaged turrets
- [ ] widget to show ship turret fire arcs, adapting to suppression/disabling of turrets
- [ ] review ship costs, perhaps bumping them upwards a tad to reduce the swarms slightly
- [x] review ship MG weapons, since some of them seem to have longer ranges than most cannons (they're not split into AA/ground variations, so they just have quite long range).

??? (add as needed)

**Comment by ashdnazg** [comment]
https://www.youtube.com/watch?v=htNI6BKjLlc

**Comment by FLOZi** [comment]
There is one example unitpic in, for BKA 1125 main turret. Can produce the rest if we like the style / icon.

Also there's the issue around targeting that still needs looking at afaik

Which children are not targetable? They all should be (but some are target-able by smallarms whilst others aren't (open vs armoured)

**Comment by ashdnazg** [comment]
![turret]
(https://raw.githubusercontent.com/spring1944/spring1944/master/unitpics/RUS_BKA_1125_Turret_76mm.png)

The icon in the bottom left is great!

**Comment by FLOZi** [comment]
Do we want different icons for open vs closed turrets?

**Comment by ashdnazg** [comment]
not sure it's worth the effort

**Comment by FLOZi** [comment]
Effort is nil apart from creating it once in the first place. It would inform the players vis a vis targeting by small arms

**Comment by ashdnazg** [comment]
so go for it :)

**Comment by kanatohodets** [comment]
The targeting issue seems to be related to LoS/Radar. With game_sensors disabled (!), a boat spawned IN LoS/radar of 20 riflemen allows individual turret targeting, and the rifles fire without any prompting. If the boat spawns out of the rifle team's LoS and then moves in, the riflemen do not fire, and I can't seem to get them to target an individual turret. Even a direct attack order on the boat doesn't stir them to shoot anything.

I tried various combinations of spawning in team LoS or team radar, but I can't find a pattern yet.

**Comment by ashdnazg** [comment]
did you try to disable https://github.com/spring1944/spring1944/blob/master/LuaRules/Gadgets/unit_hideTransported.lua as well?

**Comment by ashdnazg** [comment]
So, it was all down to canmove = false, I think it's because if your unit can't move, the engine thinks it stays in place (unlike our turrets who can wander happily around the map).

Things like disabling the move commands for children will need fixing

**Comment by kanatohodets** [comment]
Classified turrets in 248c9710a5fd47c8849f6 mostly based on the comments '-- enclosed' or '--3/4 enclosed'. This unifies the fear limits and hp values for the three categories of turret.

**Comment by kanatohodets** [comment]
Started going through ammo counts: pretty much all of the smaller weapons (20-37mm) are at 16 ammo. Larger ones (76mm-105mm) tend to be around 25. I think these are a bit high, since larger ships then consume about 1k of ammo to fully load. I suspect the right amount to fill up the biggest ships should be in the 400-600 range; the Tiger II is 416; most tanks are 150-300.

**Comment by kanatohodets** [comment]
For the twitchy-spinny behavior, I think drastically cutting down turnRates will do it, just need to find a decent balance between "fun to control" and "twitches".

**Comment by ashdnazg** [comment]
Try Spring.MoveCtrl.SetGroundMoveTypeData(unitID, "turnAccel", value)

**Comment by kanatohodets** [comment]
Things are done enough that I don't think this is still blocking -- ammo values could use more attention, might end up swinging ship HP around a bit (they might even be -too- hard to kill), but by and large this is pretty close.

**Comment by kanatohodets** [comment]
done aside from ship costs, but I think I'm happy to see how things shake out as-is.
